### ISSUE TITLE
running training with "vgg" loading network gives error. "cmu" model losees does not decrease and seems noisy 

### ISSUE THREAD

**Issue by AtousaTorabi** [ildoonet/tf-pose-estimation#112]
Hi, I am trying to reproduce original paper results based on your suggestion using vgg model. I have downlaoded openpose_vgg16.npy directly from (www.mediafire.com). which is 89.0 MB but when it load the network in (net.load()). In network_base.py at line 87 "with tf.variable_scope(op_name, reuse=True):" I get this error:
raise TypeError("VariableScope: name_or_scope must be a string or "
TypeError: VariableScope: name_or_scope must be a string or VariableScope.

I will probably investigate inside numpy file. I am just wondering if someone has had the same issue. I will appreciate any idea. 

Also I tried training using "cmu". using suggested hyperparameters. only using 32 mibinatch size. because I did not have enough GPU memory for 64. It seems the losses does not decrease and its very noisy when I  check results in tensorboard any thoughts?

 I am aware in original paper they use vgg network and "cmu" and "vgg" are also same network. why they are two options then? Thanks!

**Comment by ZhaorongHan** [comment]
The problem has been solved when i reduce the batch size to 32 , but the loss is nan and the procedure is slow ,why ?
```
[2018-03-14 14:33:29,321] [train] [INFO] prepare coordinator
[2018-03-14 14:33:29,519] [train] [INFO] Training Started.
[2018-03-14 14:35:46,653] [train] [INFO] epoch=0.03 step=100, 23.3349 examples/sec lr=0.010000, loss=nan, loss_ll=nan, loss_ll_paf=nan, loss_ll_heat=nan, q=13
[2018-03-14 14:38:38,064] [train] [INFO] epoch=0.05 step=200, 20.7426 examples/sec lr=0.010000, loss=nan, loss_ll=nan, loss_ll_paf=nan, loss_ll_heat=nan, q=2
[2018-03-14 14:41:59,817] [train] [INFO] epoch=0.08 step=300, 18.8126 examples/sec lr=0.010000, loss=nan, loss_ll=nan, loss_ll_paf=nan, loss_ll_heat=nan, q=2
[2018-03-14 14:45:13,738] [train] [INFO] epoch=0.11 step=400, 18.1762 examples/sec lr=0.010000, loss=nan, loss_ll=nan, loss_ll_paf=nan, loss_ll_heat=nan, q=2
```

**Comment by muchuanyun** [comment]
I am facing the same problem with training with "vgg". The error msg is
```
Traceback (most recent call last):
  File "train_local.py", line 190, in <module>
    net.load(pretrain_path, sess, False)
  File "/root/tf-openpose/src/network_base.py", line 87, in load
    with tf.variable_scope(op_name, reuse=True):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 1780, in __enter__
    raise TypeError("VariableScope: name_or_scope must be a string or "
TypeError: VariableScope: name_or_scope must be a string or VariableScope.
```
Training with "cmu" looks fine though. 

Any hints are appreciated!

**Comment by sarahzhouUestc** [comment]
@muchuanyun  I meet the same problem with you, have you solved it ?

**Comment by scizzzo** [comment]
@muchuanyun @sarahzhouUestc 
I think, I found the solution for this problem. In openpose_vgg16.npy items name saved as bytes not str, so there are two ways to solve it. Change type in directly in .npy file, or make several changes in network_base.py.
line 87: op_name => op_name.decode("utf-8")
line 90: param_name.decode("utf-8") => param_name
Also layers "conv5_1", "conv5_2", "conv4_3" don't exist in network, so you should delete them from .npy file

**Comment by shreyasrajesh** [comment]
@scizzzo 
I had a similar issue and tried modifying the .npy file using the below code. However, despite the datatypes seeming to be identical, the encoding in the .npy file doesn't seem to be the same and the code throws the following error.
``` 
ValueError: Variable conv5_3/biases does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=tf.AUTO_REUSE in VarScope?
```
```
arr = np.load('openpose_vgg16_old.npy')
dict_ = arr.tolist()
del dict_['conv5_1']
del dict_['conv5_2']
del dict_['conv4_3']
npy = np.array(dict, dtype = object)
np.save('openpose_vgg16.npy', npy)
```
All print and type tests seem to fine and exactly what I want. 
Any help as to what I might be doing wrong while modifying the .npy file will be great.

**Comment by shytab** [comment]
I generated a vgg19.npy from vgg19 model as the paper says it uses vgg19 instead of vgg16.
If anyone has problem in using vgg parameters as initial point for training, you can download [this file](https://drive.google.com/open?id=1_Qrpcch-RwEKKaCbrnPSoJirJjYzpxqm) for use.

**Comment by Yuliang-Zou** [comment]
Anyone replicate the results as in Caffe?

**Comment by inders** [comment]
I am still facing this. Anyone could make it work.
