### ISSUE TITLE
Errors in training

### ISSUE THREAD

**Issue by luuil** [ildoonet/tf-pose-estimation#114]
When I triaining the coco2017 dataset with cmu model  from the scratch, 

`python ./src/train.py --model=cmu --batchsize=64 --lr=0.001`

 I've got these errors:

`
Traceback (most recent call last):
  File "./src/train.py", line 70, in <module>
    df = get_dataflow_batch(args.datapath, True, args.batchsize, img_path=args.imgpath)
  File "D:\tf-pose-estimation\src\pose_dataset.py", line 380, in get_dataflow_batch
    ds = get_dataflow(path, is_train, img_path=img_path)
  File "D:\tf-pose-estimation\src\pose_dataset.py", line 367, in get_dataflow
    ds = PrefetchData(ds, 1000, multiprocessing.cpu_count() * 4)
  File "C:\Program Files\Python36\lib\site-packages\tensorpack\dataflow\parallel.py", line 185, in __init__
    start_proc_mask_signal(self.procs)
  File "C:\Program Files\Python36\lib\site-packages\tensorpack\utils\concurrency.py", line 212, in start_proc_mask_signal
    p.start()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Program Files\Python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program Files\Python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\Python36\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Program Files\Python36\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'MapDataComponent.__init__.<locals>.f'
`

My env: win10, python3.6.4(x64)
can anyone solve this?

**Comment by yw155** [comment]
Hi @luuil, this tensorflow implementation contains a package called 'tensor-pack', which is not compatible with Windows. You'd better move the codes to Linux. Thanks.

**Comment by luuil** [comment]
thanks, I'll try this.
