### ISSUE TITLE
Hi I am using tensorflow 1.4.0 following is the error i get 

### ISSUE THREAD

**Issue by govindvs** [ildoonet/tf-pose-estimation#116]
The picture i pass have only some parts of one human being.
[2018-03-13 12:59:36,469] [TfPoseEstimator] [DEBUG] inference+
[2018-03-13 12:59:36,469] [TfPoseEstimator] [DEBUG] inference+
[2018-03-13 12:59:38,347] [TfPoseEstimator] [DEBUG] inference-
[2018-03-13 12:59:38,347] [TfPoseEstimator] [DEBUG] inference-
[2018-03-13 12:59:38,866] [TfPoseEstimator] [INFO] inference image: /home/bfl/govind/tf-openpose/img_0001.png in 2.3967 seconds.
[2018-03-13 12:59:38,866] [TfPoseEstimator] [INFO] inference image: /home/bfl/govind/tf-openpose/img_0001.png in 2.3967 seconds.
Exception ignored in: <bound method TfPoseEstimator.__del__ of <estimator.TfPoseEstimator object at 0x7f43cc41b4e0>>
Traceback (most recent call last):
  File "/home/bfl/govind/tf-openpose/src/estimator.py", line 280, in __del__
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 685, in close
TypeError: 'NoneType' object is not callable

kinldy help

**Comment by ildoonet** [comment]
This error still persists?

**Comment by Necrophagistfan** [comment]
HI @ildoonet , Yes! i am getting the same error too. 

[2018-05-14 13:53:22,693] [TfPoseEstimator] [DEBUG] inference+
[2018-05-14 13:53:22,693] [TfPoseEstimator] [DEBUG] inference+
[2018-05-14 13:53:22,750] [TfPoseEstimator] [DEBUG] inference-
[2018-05-14 13:53:22,750] [TfPoseEstimator] [DEBUG] inference-
[2018-05-14 13:53:22,756] [TfPoseEstimator] [INFO] inference image: ../images/cat.jpg in 0.0652 seconds.
[2018-05-14 13:53:22,756] [TfPoseEstimator] [INFO] inference image: ../images/cat.jpg in 0.0652 seconds.
Exception ignored in: <bound method TfPoseEstimator.__del__ of <estimator.TfPoseEstimator object at 0x7fe00e795f98>>
Traceback (most recent call last):
  File "/adata/totha/tf-openpose/src/estimator.py", line 280, in __del__
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 685, in close
AttributeError: 'NoneType' object has no attribute 'raise_exception_on_not_ok_status'

Please help!

**Comment by Necrophagistfan** [comment]
@govindvs Hi, Could you fix the problem?

**Comment by ildoonet** [comment]
@Necrophagistfan Okay you can remove that line. I commited for this at 'reproduce' branch, it will be merged within few weeks. Thanks.
