### ISSUE TITLE
run train.py have a problem

### ISSUE THREAD

**Issue by ustcerman** [ildoonet/tf-pose-estimation#126]
Traceback (most recent call last):
  File "/home/hqt/PycharmProjects/openpose/tf-openpose/src/train.py", line 16, in <module>
    from pose_dataset import get_dataflow_batch, DataFlowToQueue, CocoPose
  File "/home/hqt/PycharmProjects/openpose/tf-openpose/src/pose_dataset.py", line 27, in <module>
    from tensorpack.dataflow.prefetch import PrefetchData
ModuleNotFoundError: No module named 'tensorpack.dataflow.prefetch'

I download the tensorpack0.8.6.whl and install it, but also have this problem.

**Comment by wuyuebupt** [comment]
try tensorpack 0.7.0

**Comment by ustcerman** [comment]
thanks, I change the "tensorpack.dataflow.prefetch" to "tensorpack.dataflow" ,then solve this problem
