### ISSUE TITLE
run.py: AttributeError: 'NoneType' object has no attribute 'ScopedTFStatus'

### ISSUE THREAD

**Issue by kaisark** [ildoonet/tf-pose-estimation#134]
I am running into an issue with the run.py demo for an image. [Note: the webcam demo is working]

Nvidia TX1
4 GB of RAM
GPU - Cuda 8
Ubuntu 16
tensorflow==1.5.0
tensorflow-tensorboard==1.5.1
tensorpack==0.8.5

-----------------------------------------------
(testpy3) nvidia@tegra-ubuntu:~/tf-openpose/src$ python3 run.py --model=mobilenet_thin --resolution=432x368 --image=../images/p1.jpg
2018-03-30 21:36:23.959666: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:859] ARM64 does not support NUMA - returning NUMA node zero
2018-03-30 21:36:23.959896: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1105] Found device 0 with properties: 
name: NVIDIA Tegra X1 major: 5 minor: 3 memoryClockRate(GHz): 0.9984
pciBusID: 0000:00:00.0
totalMemory: 3.89GiB freeMemory: 2.45GiB
2018-03-30 21:36:23.959944: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: NVIDIA Tegra X1, pci bus id: 0000:00:00.0, compute capability: 5.3)
[2018-03-30 21:38:54,461] [TfPoseEstimator] [DEBUG] inference+
[2018-03-30 21:38:54,461] [TfPoseEstimator] [DEBUG] inference+
[2018-03-30 21:39:02,978] [TfPoseEstimator] [DEBUG] inference-
[2018-03-30 21:39:02,978] [TfPoseEstimator] [DEBUG] inference-
[2018-03-30 21:39:03,336] [TfPoseEstimator] [INFO] inference image: ../images/p1.jpg in 17.3210 seconds.
[2018-03-30 21:39:03,336] [TfPoseEstimator] [INFO] inference image: ../images/p1.jpg in 17.3210 seconds.
Exception ignored in: <bound method TfPoseEstimator.__del__ of <estimator.TfPoseEstimator object at 0x7f58c1bcf8>>
Traceback (most recent call last):
  File "/home/nvidia/tf-openpose/src/estimator.py", line 280, in __del__
  File "/home/nvidia/.virtualenvs/testpy3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 691, in close
  File "/home/nvidia/.virtualenvs/testpy3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 464, in __enter__
AttributeError: 'NoneType' object has no attribute 'ScopedTFStatus'

**Comment by kaisark** [comment]
This looks like an image path issue...[usage]
