### ISSUE TITLE
after training, how to the trained model pb file to be used in run.py file?

### ISSUE THREAD

**Issue by tonnkie** [ildoonet/tf-pose-estimation#142]
When I tried to use the pb file I get from train.py, I gain two errors:

(1) error is the batch_size error. The batch_size of pb file asks for n (n>=2), however run.py only batch_size = 1

(2) I fix this error by changing my batch_size to 1, however, another error occurs.

from ._conv import register_converters as _register_converters
2018-04-13 11:25:15.692548: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/Users/x/Library/Python/3.5/lib/python/site-packages/tensorflow/python/client/session.py", line 1361, in _do_call
    return fn(*args)
  File "/Users/x/Library/Python/3.5/lib/python/site-packages/tensorflow/python/client/session.py", line 1332, in _run_fn
    self._extend_graph()
  File "/Users/x/Library/Python/3.5/lib/python/site-packages/tensorflow/python/client/session.py", line 1392, in _extend_graph
    graph_def.SerializeToString(), status)
  File "/Users/x/Library/Python/3.5/lib/python/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'TfPoseEstimator/Openpose/MConv_Stage5_L2_5_pointwise/BatchNorm/beta/Adam_1': Operation was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
	 [[Node: TfPoseEstimator/Openpose/MConv_Stage5_L2_5_pointwise/BatchNorm/beta/Adam_1 = VariableV2[_class=["loc:@TfPoseEstimator/Openpose/MConv_Stage5_L2_5_pointwise/BatchNorm/beta"], container="", dtype=DT_FLOAT, shape=[19], shared_name="", _device="/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/x/PycharmProjects/ali_cloth_tf4/src/run.py", line 34, in <module>
    e = TfPoseEstimator(get_graph_path(args.model), target_size=(w, h))
  File "/Users/x/PycharmProjects/ali_cloth_tf4/src/estimator.py", line 275, in __init__
    self.tensor_image: [np.ndarray(shape=(target_size[1], target_size[0], 3), dtype=np.float32)]
  File "/Users/x/Library/Python/3.5/lib/python/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/Users/x/Library/Python/3.5/lib/python/site-packages/tensorflow/python/client/session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/x/Library/Python/3.5/lib/python/site-packages/tensorflow/python/client/session.py", line 1355, in _do_run
    options, run_metadata)
  File "/Users/x/Library/Python/3.5/lib/python/site-packages/tensorflow/python/client/session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'TfPoseEstimator/Openpose/MConv_Stage5_L2_5_pointwise/BatchNorm/beta/Adam_1': Operation was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
	 [[Node: TfPoseEstimator/Openpose/MConv_Stage5_L2_5_pointwise/BatchNorm/beta/Adam_1 = VariableV2[_class=["loc:@TfPoseEstimator/Openpose/MConv_Stage5_L2_5_pointwise/BatchNorm/beta"], container="", dtype=DT_FLOAT, shape=[19], shared_name="", _device="/device:GPU:0"]()]]

Caused by op 'TfPoseEstimator/Openpose/MConv_Stage5_L2_5_pointwise/BatchNorm/beta/Adam_1', defined at:
  File "/Users/x/PycharmProjects/ali_cloth_tf4/src/run.py", line 34, in <module>
    e = TfPoseEstimator(get_graph_path(args.model), target_size=(w, h))
  File "/Users/x/PycharmProjects/ali_cloth_tf4/src/estimator.py", line 260, in __init__
    tf.import_graph_def(graph_def, name='TfPoseEstimator')
  File "/Users/x/Library/Python/3.5/lib/python/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/Users/x/Library/Python/3.5/lib/python/site-packages/tensorflow/python/framework/importer.py", line 553, in import_graph_def
    op_def=op_def)
  File "/Users/x/Library/Python/3.5/lib/python/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/Users/x/Library/Python/3.5/lib/python/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'TfPoseEstimator/Openpose/MConv_Stage5_L2_5_pointwise/BatchNorm/beta/Adam_1': Operation was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
	 [[Node: TfPoseEstimator/Openpose/MConv_Stage5_L2_5_pointwise/BatchNorm/beta/Adam_1 = VariableV2[_class=["loc:@TfPoseEstimator/Openpose/MConv_Stage5_L2_5_pointwise/BatchNorm/beta"], container="", dtype=DT_FLOAT, shape=[19], shared_name="", _device="/device:GPU:0"]()]]

Process finished with exit code 1

I don't know **how to do with this error**?
Could you show me **how you do after you train the model, and how to use it in the run.py**????
Thanks!!

**Comment by 1icas** [comment]
if you use the import_meta_graph/  . i think you can use the pamametr  clear_devices=True.  import_meta_graph(path_dir, clear_devices=True)

**Comment by shytab** [comment]
It seems your gpu device is not accessible for some reason. Maybe you can try to set device to only cpu, if this exception do not occur you need to check your gpu environment.
