### ISSUE TITLE
IOError: Failed to interpret file '/scratch2/body_pose/tf-openpose/models/numpy/openpose_coco.npy' as a pickle

### ISSUE THREAD

**Issue by monajalal** [ildoonet/tf-pose-estimation#153]
How should I fix this error?
```

[jalal@goku src]$ python eval.py --model cmu
TF<1.3 support will be removed after 2018-03-15! Actually many examples already require TF>=1.3.
2018-05-01 00:18:02.638714: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-05-01 00:18:02.638745: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-05-01 00:18:02.638754: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-05-01 00:18:02.638761: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-05-01 00:18:02.638769: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2018-05-01 00:18:02.902299: I tensorflow/core/common_runtime/gpu/gpu_device.cc:887] Found device 0 with properties: 
name: GeForce GTX 1080 Ti
major: 6 minor: 1 memoryClockRate (GHz) 1.6705
pciBusID 0000:05:00.0
Total memory: 10.92GiB
Free memory: 9.53GiB
2018-05-01 00:18:02.902435: W tensorflow/stream_executor/cuda/cuda_driver.cc:485] creating context when one is currently active; existing: 0x72a83b0
2018-05-01 00:18:03.254334: I tensorflow/core/common_runtime/gpu/gpu_device.cc:887] Found device 1 with properties: 
name: GeForce GTX 1080 Ti
major: 6 minor: 1 memoryClockRate (GHz) 1.6705
pciBusID 0000:06:00.0
Total memory: 10.92GiB
Free memory: 10.76GiB
2018-05-01 00:18:03.255336: I tensorflow/core/common_runtime/gpu/gpu_device.cc:908] DMA: 0 1 
2018-05-01 00:18:03.255363: I tensorflow/core/common_runtime/gpu/gpu_device.cc:918] 0:   Y Y 
2018-05-01 00:18:03.255375: I tensorflow/core/common_runtime/gpu/gpu_device.cc:918] 1:   Y Y 
2018-05-01 00:18:03.255410: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:05:00.0)
2018-05-01 00:18:03.255428: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:06:00.0)
Traceback (most recent call last):
  File "eval.py", line 97, in <module>
    net, _, last_layer = get_network(args.model, input_node, sess)
  File "/scratch2/body_pose/tf-openpose/src/networks.py", line 51, in get_network
    net.load(os.path.join(_get_base_path(), pretrain_path), sess_for_load)
  File "/scratch2/body_pose/tf-openpose/src/network_base.py", line 73, in load
    data_dict = np.load(data_path, encoding='bytes').item()
  File "/usr/lib64/python2.7/site-packages/numpy/lib/npyio.py", line 429, in load
    "Failed to interpret file %s as a pickle" % repr(file))
IOError: Failed to interpret file '/scratch2/body_pose/tf-openpose/models/numpy/openpose_coco.npy' as a pickle

```

**Comment by ildoonet** [comment]
This is not my code.
