### ISSUE TITLE
Training: Thread.__init__() not called

### ISSUE THREAD

**Issue by sri123098** [ildoonet/tf-pose-estimation#164]
Dear all
When I'm running the training, I'm getting the following issue. 

[0509 11:02:00 @parallel.py:185] [MultiProcessPrefetchData] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
[0509 11:02:00 @parallel.py:185] [MultiProcessPrefetchData] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
Traceback (most recent call last):
  File "src/train.py", line 74, in <module>
    enqueuer = DataFlowToQueue(df, [input_node, heatmap_node, vectmap_node], queue_size=100)
  File "/Users/sriramreddy/PycharmProjects/RBG/tf-pose-estimation/src/pose_dataset.py", line 393, in __init__
    self.daemon = True
  File "/Users/sriramreddy/anaconda3/lib/python3.6/threading.py", line 1139, in daemon
    raise RuntimeError("Thread.__init__() not called")
RuntimeError: Thread.__init__() not called

The command which I'm using to run the training.
python src/train.py --model=cmu --datapath={/Users/sriramreddy/PycharmProjects/RBG/keras_Realtime_Multi-Person_Pose_Estimation/dataset/train2017} --batchsize=64 --lr=0.001 --modelpath={/Users/sriramreddy/PycharmProjects/RBG/}

Could you please help me with this ?

Thanks,
Sriram

**Comment by xiaofeiwu** [comment]
I met similar problem and didn't resolve it up to now.

**Comment by ouceduxzk** [comment]
@sri123098  hey, you are running the keras implementation and ask questions here. is that a typo or not? I never have such problem before, please specify what kind of os, environment are you running if it is a typo

**Comment by geralt777** [comment]
hi..
I've tried to run the training.py file as instructed in the link: 
https://github.com/ildoonet/tf-pose-estimation/blob/master/etcs/training.md
But, i'm running into the same thread error as mentioned above.
Maybe there is some instruction that wasn't mentioned or could be an issue with the code itself...
PS- I'm running it on Ubuntu with a NVIDIA 1070 gtx card

**Comment by bllxk** [comment]
I also met similar problem,so I added ''threading.Thread.__init__(self)" before "self.daemon = True" in line 393.And then the problem is solved.
