### ISSUE TITLE
What happened to my program caused me not to proceed?  from estimator import TfPoseEstimator ImportError: cannot import name 'pafprocess'

### ISSUE THREAD

**Issue by zerolim820** [ildoonet/tf-pose-estimation#191]
(tfpose) C:\Users\lim_l_000\Desktop\tf-openpose>python src/run_webcam.py --model=mobilenet_thin_432x368 --camera=0
Traceback (most recent call last):
  File "src/run_webcam.py", line 8, in <module>
    from estimator import TfPoseEstimator
  File "C:\Users\lim_l_000\Desktop\tf-openpose\src\estimator.py", line 5, in <module>
    from pafprocess import pafprocess
ImportError: cannot import name 'pafprocess'

**Comment by ouceduxzk** [comment]
please compile pafprocess first with swig inside the srf/pafprocess folder

**Comment by zerolim820** [comment]
can teach me how to do it ...?
I am a beginner...
u mean is install swig ?

**Comment by siddharthrajpatel** [comment]
hi @ouceduxzk , @RitvikMandyam  i have run the command in the src\pafprocess location:

swig -python -c++ pafprocess.i && python3 setup.py build_ext --inplace
but it shows the following error:

![pa](https://user-images.githubusercontent.com/36742332/40764692-a998e0ee-64c7-11e8-9a72-e72feda9bbd1.JPG)

can you please help?

**Comment by zerolim820** [comment]
I did that but it still has problems .....

(tfpose) C:\Users\lim_l_000\Desktop\tf-pose2\tf_pose\pafprocess>swig -python -c++ pafprocess.i && python setup.py build_ext --inplace
running build_ext
building '_pafprocess' extension
swigging pafprocess.i to pafprocess_wrap.cpp
C:\Program Files\swigwin-3.0.12\swig.exe -python -c++ -o pafprocess_wrap.cpp pafprocess.i
error: Unable to find vcvarsall.bat

**Comment by riccardoPalumbo96** [comment]
@siddharthrajpatel  Hi bro! I've someway managed this error by replacing all "or" with "||"  and all "and" with "&&". Also it need to change the round function name (i've named it as "rounds") beacuse it collides with cmath round function. Now you have just to run "swig -python -c++ pafprocess.i && python setup.py build_ext --inplace
" and it will compile. Then should work everything (hope it!).﻿

**Comment by Nilanshrajput** [comment]
@zerolim820 
I also faced the same problem...

(tfpose) C:\Users\lim_l_000\Desktop\tf-pose2\tf_pose\pafprocess>swig -python -c++ pafprocess.i && python setup.py build_ext --inplace
running build_ext
building '_pafprocess' extension
swigging pafprocess.i to pafprocess_wrap.cpp
C:\Program Files\swigwin-3.0.12\swig.exe -python -c++ -o pafprocess_wrap.cpp pafprocess.i
error: Unable to find vcvarsall.bat

**Comment by RitvikMandyam** [comment]
Try installing Visual Studio. If my memory serves, vcvarsall.bat is part of the VS package.

**Comment by siddharthrajpatel** [comment]
@riccardoPalumbo96 thanks, now the swig code is running :)

**Comment by yinan-1** [comment]
This error always occurs.
> error: Unable to find vcvarsall.bat

**Comment by yinan-1** [comment]
This error always occurs.
`(tfpose) C:\Users\15029\Desktop\tf-openpose\tf_pose\pafprocess>swig -python -c++ pafprocess.i && python setup.py build_ext --inplace
running build_ext
building '_pafprocess' extension
swigging pafprocess.i to pafprocess_wrap.cpp
C:\Users\15029\Anaconda3\Library\bin\swig.exe -python -c++ -o pafprocess_wrap.cpp pafprocess.i
error: Unable to find vcvarsall.bat
`

**Comment by yinan-1** [comment]
This error always occurs.

> (tfpose) C:\Users\15029\Desktop\tf-openpose\tf_pose\pafprocess>swig -python -c++ pafprocess.i && python setup.py build_ext --inplace
running build_ext
building '_pafprocess' extension
swigging pafprocess.i to pafprocess_wrap.cpp
C:\Users\15029\Anaconda3\Library\bin\swig.exe -python -c++ -o pafprocess_wrap.cpp pafprocess.i
error: Unable to find vcvarsall.bat

**Comment by riccardoPalumbo96** [comment]
Try to compile directly from Visual Studio Prompt
This could be useful: https://blogs.msdn.microsoft.com/pythonengineering/2016/04/11/unable-to-find-vcvarsall-bat/

**Comment by yinan-1** [comment]
Thx. i reinstalled Visual Studio2017 and solved the problem.

**Comment by Ramo19** [comment]
@yinan-1 when you reinstall VS2017, are u repeat all commands ?

**Comment by yinan-1** [comment]
No, I'm just missing the C++ environment.

发件人: Omar El Manssouri
发送时间: 2018年10月28日 5:39
收件人: ildoonet/tf-pose-estimation
抄送: yinan-1; Mention
主题: Re: [ildoonet/tf-pose-estimation] What happened to my program causedme not to proceed? from estimator import TfPoseEstimator ImportError: cannotimport name 'pafprocess' (#191)

@yinan-1 when you reinstall VS2017, are u repeat all commands ?

**Comment by FrancisLeung** [comment]
Hi,
I got problem when running command of either "python run_webcam.py --model=mobilenet_thin --resize=432x368 --camera=0" or "python3 run_webcam.py --model=mobilenet_thin --resize=432x368 --camera=0"

Error shown below when set root to run tf-pose:
"root@ired-IdeaPad-L340-15IRH-Gaming:/Downloads/tf-pose-estimation-master# python run_webcam.py --model=mobilenet_thin --resize=432x368 --camera=0
Traceback (most recent call last):
File "run_webcam.py", line 8, in
from tf_pose.estimator import TfPoseEstimator
File "/home/ired/Downloads/tf-pose-estimation-master/tf_pose/init.py", line 5, in
from tf_pose.runner import infer, Estimator, get_estimator
File "/home/ired/Downloads/tf-pose-estimation-master/tf_pose/runner.py", line 5, in
from functools import lru_cache
ImportError: cannot import name lru_cache
root@ired-IdeaPad-L340-15IRH-Gaming:/Downloads/tf-pose-estimation-master# python3 run.py --model=mobilenet_thin --resize=432x368 --image=./images/p1.jpg
Traceback (most recent call last):
File "run.py", line 6, in
from tf_pose import common
File "/home/ired/Downloads/tf-pose-estimation-master/tf_pose/init.py", line 5, in
from tf_pose.runner import infer, Estimator, get_estimator
File "/home/ired/Downloads/tf-pose-estimation-master/tf_pose/runner.py", line 4, in
import cv2
ModuleNotFoundError: No module named 'cv2'"

Could anyone tell me how to fix it please?
Thanks, Francis
