### ISSUE TITLE
models/numpy/donwload.sh cannot download npy file

### ISSUE THREAD

**Issue by toshiy104** [ildoonet/tf-pose-estimation#194]
The contents of model/numpy/donwload.sh are as follows
#!/bin/bash

wget http://www.mediafire.com/file/ropayv77vklvf56/openpose_coco.npy
wget http://www.mediafire.com/file/7e73ddj31rzw6qq/openpose_vgg16.npy

these two urls are just links to html, so wget cannot download npy file.
to download npy file, access http://www.mediafire.com/file/ropayv77vklvf56/openpose_coco.npy with
browser, and must click DOWNLOAD button.

**Comment by ildoonet** [comment]
Thanks for reporting this. I will change the bash script.

**Comment by luckhhn** [comment]
sir ,I downloaded the openpose_coco.pny from http://www.mediafire.com/file/ropayv77vklvf56/openpose_coco.npy

but ,run realtime _webcam is wrong

Traceback (most recent call last):
  File "F:/PythonProject/gait-me/openpose/realtime_webcam_save.py", line 70, in <module>
    net, _, last_layer = get_network(args.model, input_node, sess)
  File "F:\PythonProject\gait-me\openpose\networks.py", line 37, in get_network
    net.load('./models/numpy/openpose_coco.npy', sess_for_load)
  File "F:\PythonProject\gait-me\openpose\network_base.py", line 66, in load
    data_dict = np.load(data_path, encoding='bytes').item()
  File "D:\ProgramData\Anaconda3\envs\tensorflow-gpu\lib\site-packages\numpy\lib\npyio.py", line 433, in load
    pickle_kwargs=pickle_kwargs)
  File "D:\ProgramData\Anaconda3\envs\tensorflow-gpu\lib\site-packages\numpy\lib\format.py", line 657, in read_array
    array = pickle.load(fp, **pickle_kwargs)
_pickle.UnpicklingError: pickle data was truncated

**Comment by luckhhn** [comment]
@toshiy104  thanks for your help
