### ISSUE TITLE
Data loading during training

### ISSUE THREAD

**Issue by Yuliang-Zou** [ildoonet/tf-pose-estimation#197]
Hi, thanks for sharing the well written code!

I am trying to reproduce the original paper's result according to the instructions. However, I found that after testing on the validation set, it will output error messages as below

```
500it [17:26,  2.09s/it]
[2018-05-31 10:57:46,833] [train] [INFO] validation(5000) vgg_batch:10_lr:0.0001_gpus:1_368x368_ loss=332.749305, loss_ll=66.225111, loss_ll_
paf=90.833312, loss_ll_heat=41.616910
2018-05-31 10:57:46.835404: W tensorflow/core/kernels/queue_base.cc:295] _0_fifo_queue: Skipping cancelled enqueue attempt with queue not clo
sed
Traceback (most recent call last):
  File "src/train.py", line 253, in <module>
[2018-05-31 10:57:46,836] [pose_dataset] [ERROR] err type1, placeholders=[<tf.Tensor 'image:0' shape=(10, 368, 368, 3) dtype=float32>, <tf.Te
nsor 'heatmap:0' shape=(10, 46, 46, 19) dtype=float32>, <tf.Tensor 'vectmap:0' shape=(10, 46, 46, 38) dtype=float32>]
[2018-05-31 10:57:46,836] [pose_dataset] [INFO] Thread-1 Exited.
    feed_dict={q_inp: np.array((sample_image + val_image)*(args.batchsize // 16))}
  File "/mnt/ilcompf6d1/user/yuzou/install/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/mnt/ilcompf6d1/user/yuzou/install/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1096, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (0,) for Tensor 'fifo_queue_Dequeue:0', which has shape '(10, 368, 368, 3)'
``` 

And if I remove the testing part, the training seems fine. Do you have any thoughts what could be the reason?

**Comment by toshiy104** [comment]
probably you specified --batchsize=10 when running train.py.
changing it to --batchsize = 16.
because at 251 line of train.py, length of (sample_image + val_image) equals to 16,
and multiplied by (args.batchsize / 16).

**Comment by Yuliang-Zou** [comment]
@toshiy104 I see. Thanks!

**Comment by Yuliang-Zou** [comment]
@sanwong15 I modified several lines according to the error message. Can you tell us what's your error?

**Comment by Naykira** [comment]
Hi everyone, I am running into a similar error when training. I have the batchsize = 16 already set so that cannot be the error. Any other suggestions that can solve this issue would be very helpful. Thanks!

**Comment by chrisskab** [comment]
@Naykira @Yuliang-Zou @toshiy104 @sanwong15 @kimdwkimdw  Did anyone figured this out ? I have a similar error
