### ISSUE TITLE
 Resource exhausted error when training

### ISSUE THREAD

**Issue by lyyiangang** [ildoonet/tf-pose-estimation#201]
I am trying to train model.  But meet some errors. My gpu is nvidia GTX1060 6g version.
I use the train.py like this :
```
python3 ./src/train.py \
--model "cmu" \
--datapath "/media/lyy/dataset/coco-data/coco2017/annotations_trainval2017/annotations" \
--imgpath "/media/lyy/dataset/coco-data/coco2017/imgs/" \
--batchsize 16 \
--modelpath "./train_model" \
--logpath "./logs"
```
but get following error. 
```
2018-06-02 13:26:47.411476: I tensorflow/core/common_runtime/bfc_allocator.cc:674] 2 Chunks of size 277348352 totalling 529.00MiB
2018-06-02 13:26:47.411484: I tensorflow/core/common_runtime/bfc_allocator.cc:674] 2 Chunks of size 554696704 totalling 1.03GiB
2018-06-02 13:26:47.411492: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Sum Total of in-use chunks: 4.72GiB
2018-06-02 13:26:47.411505: I tensorflow/core/common_runtime/bfc_allocator.cc:680] Stats:
Limit:                  5093090918
InUse:                  5070107904
MaxInUse:               5082934272
NumAllocs:                    1675
MaxAllocSize:           1378202368

2018-06-02 13:26:47.411571: W tensorflow/core/common_runtime/bfc_allocator.cc:279] ****************************************************************************************************
2018-06-02 13:26:47.411611: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at conv_ops.cc:673 : Resource exhausted: OOM when allocating tensor with shape[16,128,46,46] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
[2018-06-02 13:27:01,051] [pose_dataset] [ERROR] err type2, err=Attempted to use a closed Session., placeholders=[<tf.Tensor 'image:0' shape=(16,368, 368, 3) dtype=float32>, <tf.Tensor 'heatmap:0' shape=(16, 46, 46, 19) dtype=float32>, <tf.Tensor 'vectmap:0' shape=(16, 46, 46, 38) dtype=float32>]
[2018-06-02 13:27:02,784] [pose_dataset] [INFO] Thread-1 Exited.
Traceback (most recent call last):
  File "/home/lyy/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/lyy/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/lyy/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[16,128,46,46] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[Node: Mconv5_stage6_L1/Conv2D = Conv2D[T=DT_FLOAT, _class=["loc:@gradients/Mconv5_stage6_L1/Conv2D_grad/Conv2DBackpropInput"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Mconv4_stage6_L1/Mconv4_stage6_L1, Mconv5_stage6_L1/weights/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[Node: Adam/update/_406 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_4277_Adam/update", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
```

**Comment by lyyiangang** [comment]
I fix this problem at last. Just use smaller image size and batch size.

**Comment by Naykira** [comment]
Hi @lyyiangang, I am facing the same issue. What image size and batchsize did you finally use?

**Comment by mrkaworu** [comment]
I'll like to know the values too!
