### ISSUE TITLE
test installed package:python -c 'import tf_pose; tf_pose.infer(image="./images/p1.jpg")'

### ISSUE THREAD

**Issue by tianjiahao** [ildoonet/tf-pose-estimation#241]
C:\Users\Administrator\Desktop\tf-pose-estimation-master>python
Python 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tf_pose
>>> tf_pose.infer(image="./images/p1.jpg")
[2018-06-27 20:06:19,943] [TfPoseEstimator] [INFO] loading graph from ./models/graph/cmu/graph_opt.pb(default size=432x368)
2018-06-27 20:06:24.140624: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:1030] Found device 0 with properties:
name: GeForce GTX 1060 6GB major: 6 minor: 1 memoryClockRate(GHz): 1.7845
pciBusID: 0000:22:00.0
totalMemory: 6.00GiB freeMemory: 5.01GiB
2018-06-27 20:06:24.146927: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:22:00.0, compute capability: 6.1)
2018-06-27 20:06:30.993589: E C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\common_runtime\executor.cc:643] Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: TfPoseEstimator/conv1_1/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](TfPoseEstimator/preprocess_subtract, TfPoseEstimator/conv1_1/weights). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
         [[Node: TfPoseEstimator/conv1_1/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](TfPoseEstimator/preprocess_subtract, TfPoseEstimator/conv1_1/weights)]]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1323, in _do_call
    return fn(*args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1302, in _run_fn
    status, run_metadata)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: TfPoseEstimator/conv1_1/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](TfPoseEstimator/preprocess_subtract, TfPoseEstimator/conv1_1/weights). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
         [[Node: TfPoseEstimator/conv1_1/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](TfPoseEstimator/preprocess_subtract, TfPoseEstimator/conv1_1/weights)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\Desktop\tf-pose-estimation-master\tf_pose\runner.py", line 35, in infer
    e = TfPoseEstimator(get_graph_path(model), target_size=(432, 368))
  File "C:\Users\Administrator\Desktop\tf-pose-estimation-master\tf_pose\estimator.py", line 186, in __init__
    self.upsample_size: [target_size[1], target_size[0]]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 889, in run
    run_metadata_ptr)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1317, in _do_run
    options, run_metadata)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: TfPoseEstimator/conv1_1/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](TfPoseEstimator/preprocess_subtract, TfPoseEstimator/conv1_1/weights). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
         [[Node: TfPoseEstimator/conv1_1/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](TfPoseEstimator/preprocess_subtract, TfPoseEstimator/conv1_1/weights)]]

Caused by op 'TfPoseEstimator/conv1_1/Conv2D', defined at:
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\Desktop\tf-pose-estimation-master\tf_pose\runner.py", line 35, in infer
    e = TfPoseEstimator(get_graph_path(model), target_size=(432, 368))
  File "C:\Users\Administrator\Desktop\tf-pose-estimation-master\tf_pose\estimator.py", line 149, in __init__
    tf.import_graph_def(graph_def, name='TfPoseEstimator')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\importer.py", line 313, in import_graph_def
    op_def=op_def)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 2956, in create_op
    op_def=op_def)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: TfPoseEstimator/conv1_1/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](TfPoseEstimator/preprocess_subtract, TfPoseEstimator/conv1_1/weights). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
         [[Node: TfPoseEstimator/conv1_1/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](TfPoseEstimator/preprocess_subtract, TfPoseEstimator/conv1_1/weights)]]

**Comment by newchuchao** [comment]
hi,how to use ildoonet/tf-pose-estimation,can you tell me something about it?

**Comment by zhangxiaopang88** [comment]
我也遇到此类问题，现在还没解决，请问您解决了吗，怎么解决的

**Comment by zhangxiaopang88** [comment]
hi ，Is your problem solved?I have also encountered this kind of problem, has not solved now, excuse me has any good method?

**Comment by elkalash** [comment]
你们在用CPU还是GPU'?

**Comment by dlwogns0128** [comment]
I think you have to upgrade tensroflow version. Look at #205
