### ISSUE TITLE
Create inference model for mobilenet

### ISSUE THREAD

**Issue by scofield1991** [ildoonet/tf-pose-estimation#246]
Cannot create inference model for mobilenet. Get an error:
def upsample(self, input, factor, name):
--> 172         return tf.image.resize_bilinear(input, [int(input.get_shape()[1]) * factor, int(input.get_shape()[2]) * factor], name=name)
    173 
    174     @layer

TypeError: __int__ returned non-int (type NoneType)

How to create inference model for Mobilenet?

**Comment by tzolov** [comment]
Same issue here, while trying to  generate a frozen `mobilenet_fast` model using the pre-trained weights in `models/pretrained/`

After installing the latest tf-pose-estimation and TF 1.8.0 i run:
```
python3 ./run_checkpoint.py --model=mobilenet_fast
```
But got following error:
```
Traceback (most recent call last):
  File "./run_checkpoint.py", line 27, in <module>
    net, _, last_layer = get_network(args.model, input_node, sess, trainable=False)
  File "/tf-pose-estimation/tf_pose/networks.py", line 24, in get_network
    net = MobilenetNetwork({'image': placeholder_input}, conv_width=0.5, conv_width2=0.5, trainable=trainable)
  File "/tf-pose-estimation/tf_pose/network_mobilenet.py", line 13, in __init__
    network_base.BaseNetwork.__init__(self, inputs, trainable)
  File "/tf-pose-estimation/tf_pose/network_base.py", line 63, in __init__
    self.setup()
  File "/tf-pose-estimation/tf_pose/network_mobilenet.py", line 39, in setup
    (self.feed('Conv2d_7').upsample(2, name='Conv2d_7_upsample'))
  File "/tf-pose-estimation/tf_pose/network_base.py", line 38, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "/tf-pose-estimation/tf_pose/network_base.py", line 168, in upsample
    return tf.image.resize_bilinear(input, [int(input.get_shape()[1]) * factor, int(input.get_shape()[2]) * factor], name=name)
TypeError: __int__ returned non-int (type NoneType)
```

Perhaps i am missing some configuration or prerequisite step(s)?

**Comment by zjbabylove** [comment]
@scofield1991 @tzolov
I  get the same error here, have you found a solution？

**Comment by tzolov** [comment]
@zjbabylove no I'm still stack here. Any progress on your side?

**Comment by 1icas** [comment]
you should ensure the input_node shape when you create inference model, if you use the tf.image.resize_bilinear
