### ISSUE TITLE
ValueError,when I train with 'cmu' model

### ISSUE THREAD

**Issue by GSGSZhang** [ildoonet/tf-pose-estimation#258]
[2018-07-09 11:09:38,928] [train] [INFO] Training Started.
[2018-07-09 11:09:41,592] [pose_dataset] [ERROR] err type2, err=Cannot feed value of shape (64, 184, 184, 19) for Tensor 'heatmap:0', which has shape '(64, 46, 46, 19)', placeholders=[<tf.Tensor 'image:0' shape=(64, 368, 368, 3) dtype=float32>, <tf.Tensor 'heatmap:0' shape=(64, 46, 46, 19) dtype=float32>, <tf.Tensor 'vectmap:0' shape=(64, 46, 46, 38) dtype=float32>]
[2018-07-09 11:09:41,601] [pose_dataset] [ERROR] Exception in Thread-1:Cannot feed value of shape (64, 184, 184, 19) for Tensor 'heatmap:0', which has shape '(64, 46, 46, 19)'
Traceback (most recent call last):
  File "/home/jp/Downloads/tf-pose-estimation-master/tf_pose/pose_dataset.py", line 442, in run
    self.op.run(feed_dict=feed)
  File "/home/jp/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2377, in run
    _run_using_default_session(self, feed_dict, self.graph, session)
  File "/home/jp/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 5215, in _run_using_default_session
    session.run(operation, feed_dict)
  File "/home/jp/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/jp/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1111, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (64, 184, 184, 19) for Tensor 'heatmap:0', which has shape '(64, 46, 46, 19)'
[2018-07-09 11:09:42,323] [pose_dataset] [INFO] Thread-1 Exited.

**Comment by shreyasrajesh** [comment]
Hi, 
I am getting the same error. Were you able to fix it ? What was the issue ?

**Comment by Laura9505** [comment]
Hi, I am getting the same error. How did you fix it?

ValueError: Dimension 2 in both shapes must be equal, but are 128 and 64. Shapes are [1,1,128,19] and [1,1,64,19]. for 'Mconv7_stage3_L2_1/Assign' (op: 'Assign') with input shapes: [1,1,128,19], [1,1,64,19].
