### ISSUE TITLE
ValueError，when I trained with cmu model

### ISSUE THREAD

**Issue by GSGSZhang** [ildoonet/tf-pose-estimation#260]
I just trained as the training.md do, then I got the  following issue:
[2018-07-09 11:56:52,787] [train] [INFO] Training Started.
[2018-07-09 11:57:00,044] [pose_dataset] [ERROR] err type2, err=Cannot feed value of shape (64, 184, 184, 19) for Tensor 'heatmap:0', which has shape '(64, 46, 46, 19)', placeholders=[<tf.Tensor 'image:0' shape=(64, 368, 368, 3) dtype=float32>, <tf.Tensor 'heatmap:0' shape=(64, 46, 46, 19) dtype=float32>, <tf.Tensor 'vectmap:0' shape=(64, 46, 46, 38) dtype=float32>]
[2018-07-09 11:57:00,046] [pose_dataset] [ERROR] Exception in Thread-1:Cannot feed value of shape (64, 184, 184, 19) for Tensor 'heatmap:0', which has shape '(64, 46, 46, 19)'
Traceback (most recent call last):
  File "/home/jp/Downloads/tf-pose-estimation-master/tf_pose/pose_dataset.py", line 442, in run
    self.op.run(feed_dict=feed)
  File "/home/jp/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2377, in run
    _run_using_default_session(self, feed_dict, self.graph, session)
  File "/home/jp/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 5215, in _run_using_default_session
    session.run(operation, feed_dict)
  File "/home/jp/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/jp/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1111, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (64, 184, 184, 19) for Tensor 'heatmap:0', which has shape '(64, 46, 46, 19)'
[2018-07-09 11:57:13,553] [pose_dataset] [INFO] Thread-1 Exited.

Please help
Thanks!

**Comment by nathansuw** [comment]
I'm having the same issue with training where I'm running into a tensor shape mismatch right as training starts. I've tried using the CMU and mobilenet models with no luck. Were you able to resolve this?

**Comment by shreyasrajesh** [comment]
Hi,
I am getting the same error. Were you able to fix it ? What was the issue ?

**Comment by Naykira** [comment]
Hello @GSGSZhang and @nathansuw! Were you able to solve this problem? If yes, could you please share the solution? Thanks!

**Comment by zikuicai** [comment]
Hi all, did you solve the problem? If not, try to reduce the batch size, e.g. 32 or smaller, and see if it works. I referred to this issue #119 and somehow it worked out, although it's a different error.

**Comment by Naykira** [comment]
Hi! Thanks for the suggestion but unfortunately, my batch size is already 16.

**Comment by mrkaworu** [comment]
Somebody has any feedback about this problem?

**Comment by marlon-bain** [comment]
It has to do with `tf_pose/pose_augment.py` and its "set scale" function not working properly. On the CMU model, the scale should be set to 8. Try hard-coding the value of `_scale` near the top to 8 and see if that helps.
