### ISSUE TITLE
run_video.py example? and any parameters to activate saving?

### ISSUE THREAD

**Issue by jiapei100** [ildoonet/tf-pose-estimation#266]
Hi, any example for run_video.py ?
And is there a parameter for recording?

Cheers
Pei

**Comment by elbekri** [comment]
`import argparse
import logging
import time

import cv2
import numpy as np

from tf_pose.estimator import TfPoseEstimator
from tf_pose.networks import get_graph_path, model_wh

logger = logging.getLogger('TfPoseEstimator-Video')
logger.setLevel(logging.DEBUG)
ch = logging.StreamHandler()
ch.setLevel(logging.DEBUG)
formatter = logging.Formatter('[%(asctime)s] [%(name)s] [%(levelname)s] %(message)s')
ch.setFormatter(formatter)
logger.addHandler(ch)

fps_time = 0


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='tf-pose-estimation Video')
    parser.add_argument('--video', type=str, default='')
    parser.add_argument('--write_video', type=str, default='')
    parser.add_argument('--resolution', type=str, default='432x368', help='network input resolution. default=432x368')
    parser.add_argument('--model', type=str, default='mobilenet_thin', help='cmu / mobilenet_thin')
    parser.add_argument('--show-process', type=bool, default=False,
                        help='for debug purpose, if enabled, speed for inference is dropped.')
    parser.add_argument('--showBG', type=bool, default=True, help='False to show skeleton only.')
    args = parser.parse_args()

    logger.debug('initialization %s : %s' % (args.model, get_graph_path(args.model)))
    w, h = model_wh(args.resolution)
    e = TfPoseEstimator(get_graph_path(args.model), target_size=(w, h))
    cap = cv2.VideoCapture(args.video)
    if args.write_video:
        # Define the codec and create VideoWriter object
        fourcc = cv2.VideoWriter_fourcc(*'XVID')
        out = cv2.VideoWriter(args.write_video,fourcc, 20.0, (432,368))

    if cap.isOpened() is False:
        print("Error opening video stream or file")
    while cap.isOpened():
        ret_val, image = cap.read()
        if ret_val==True:
            humans = e.inference(image)
            if not args.showBG:
                image = np.zeros(image.shape)
            image = TfPoseEstimator.draw_humans(image, humans, imgcopy=False)

            cv2.putText(image, "FPS: %f" % (1.0 / (time.time() - fps_time)), (10, 10),  cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)
            if args.write_video:
                out.write(image)
            else:
                cv2.imshow('tf-pose-estimation result', image)
            fps_time = time.time()
            if cv2.waitKey(1) == 27:
                break
        else:
            break
    cap.release()
    out.release()
    cv2.destroyAllWindows()
logger.debug('finished+')
`
you can change run_video.py to that then you'll have an option for saving the video.
And to use it it's really easy two just type something like that "python run_video.py --video=../videoplayback.avi --write_video=../results.avi"

**Comment by KristianDukov** [comment]
Hello @elbekri 

I created a new file with the code above and once I try to run it with the following arguments: 
`run_video_test.py --video yes_720.avi --write_video demo.avi`
I get the following error:

```
Traceback (most recent call last):
  File "run_video_test.py", line 51, in <module>
    humans = e.inference(image, resize_to_default=(w > 0 and h > 0), upsample_size=4.0)
  File "C:\tf-pose-estimation\tf-openpose\tf_pose\estimator.py", line 510, in inference
    raise Exception('The image is not valid. Please check your image exists.')
Exception: The image is not valid. Please check your image exists.
```
Is there something else to be changed?

**Comment by elbekri** [comment]
You must type the path of your video if it's in the same directory you shall type run_video_test.py --video=./yes_720.avi --write_video=./demo.avi

**Comment by TheGreatLeoX** [comment]
> Hello @elbekri
> 
> I created a new file with the code above and once I try to run it with the following arguments:
> `run_video_test.py --video yes_720.avi --write_video demo.avi`
> I get the following error:
> 
> ```
> Traceback (most recent call last):
>   File "run_video_test.py", line 51, in <module>
>     humans = e.inference(image, resize_to_default=(w > 0 and h > 0), upsample_size=4.0)
>   File "C:\tf-pose-estimation\tf-openpose\tf_pose\estimator.py", line 510, in inference
>     raise Exception('The image is not valid. Please check your image exists.')
> Exception: The image is not valid. Please check your image exists.
> ```
> 
> Is there something else to be changed?

Hi, I had the same error report.

I enter this,
`python newvideo2.py --video=./etcs/dance.mp4 --write_video=./save_test/video/1.mp4`
and get the report,

```
Traceback (most recent call last): 
    File "newvideo2.py", line 55, in <module>
    humans = e.inference(image, resize_to_default=(w > 0 and h > 0), upsample_size=4.0)
  File "/sdb/tmp/users/xiongja/tf-pose-estimation-master/tf_pose/estimator.py", line 537, in inference
    raise Exception('The image is not valid. Please check your image exists.')
Exception: The image is not valid. Please check your image exists.

```

Have you solved this problem?

**Comment by Leochens** [comment]
I found a method to solve this problem.
the size of output video must be matched with the input source video.
please take a look at my code bellow.
hope it will help all of you.
be aware of the code-line which marked by line.
`
import argparse
import logging
import time

import cv2
import numpy as np

from tf_pose.estimator import TfPoseEstimator
from tf_pose.networks import get_graph_path, model_wh

logger = logging.getLogger('TfPoseEstimator-Video')
logger.setLevel(logging.DEBUG)
ch = logging.StreamHandler()
ch.setLevel(logging.DEBUG)
formatter = logging.Formatter(
    '[%(asctime)s] [%(name)s] [%(levelname)s] %(message)s')
ch.setFormatter(formatter)
logger.addHandler(ch)

fps_time = 0

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='tf-pose-estimation Video')
    parser.add_argument('--video', type=str, default='')
    parser.add_argument('--write_video', type=str, default='')
    parser.add_argument('--resolution', type=str, default='432x368',
                        help='network input resolution. default=432x368')
    parser.add_argument('--model', type=str,
                        default='mobilenet_thin', help='cmu / mobilenet_thin')
    parser.add_argument('--show-process', type=bool, default=False,
                        help='for debug purpose, if enabled, speed for inference is dropped.')
    parser.add_argument('--showBG', type=str, default='',
                        help='Use it with any non-empty string to show skeleton only.')
    args = parser.parse_args()

    logger.debug('initialization %s : %s' %
                 (args.model, get_graph_path(args.model)))
    w, h = model_wh(args.resolution)
    if w > 0 and h > 0:
        e = TfPoseEstimator(get_graph_path(args.model), target_size=(w, h))
    else:
        e = TfPoseEstimator(get_graph_path(args.model), target_size=(432, 368))
    logger.debug('video read+')
    cap = cv2.VideoCapture(args.video)

    #---------------------------------
    frame_width = int(cap.get(3))
    frame_height = int(cap.get(4))
    #---------------------------------

    if args.write_video:
        # Define the codec and create VideoWriter object
        fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    #---------------------------------
        out = cv2.VideoWriter(args.write_video, fourcc, 20.0, (frame_width,frame_height)) # LOOK AT THIS
    #---------------------------------

    ret_val, image = cap.read()
    logger.info('cap image=%dx%d' % (image.shape[1], image.shape[0]))

    if cap.isOpened() is False:
        print("Error opening video stream or file")
    while cap.isOpened():
        ret_val, image = cap.read()
        if(image is None):
            break

        humans = e.inference(image, resize_to_default=True, upsample_size=4.0)
        if args.showBG:
            image = np.zeros(image.shape, dtype=np.uint8)
        image = TfPoseEstimator.draw_humans(image, humans, imgcopy=False)

        cv2.putText(image, "FPS: %f" % (1.0 / (time.time() - fps_time)),
                    (10, 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)
        if args.write_video:
            cv2.imshow('tf-pose-estimation result', image)
            out.write(image)
            print(type(image))
            print("...")
        else:
            cv2.imshow('tf-pose-estimation result', image)
            print(",,,")

        fps_time = time.time()
        if cv2.waitKey(1) == 27:
            break
    cap.release()
    out.release()
    cv2.destroyAllWindows()
logger.debug('finished+')

`

**Comment by Estebandobrasil** [comment]
Hello elbekri, thank you very much. I tried your code but I get the following error message: 
ImportError: cannot import name 'TfPoseEstimator' from 'estimator' (C:\Users\etien\AppData\Local\Programs\Python\Python37\lib\site-packages\estimator\__init__.py)
Do you have an idea what may cause this issue? Thanks !!

**Comment by elbekri** [comment]
> Hello elbekri, thank you very much. I tried your code but I get the following error message:
> ImportError: cannot import name 'TfPoseEstimator' from 'estimator' (C:\Users\etien\AppData\Local\Programs\Python\Python37\lib\site-packages\estimator__init__.py)
> Do you have an idea what may cause this issue? Thanks !!

This is an issue with your tensorflow lib, maybe not the right version or maybe it was installed for another env.
Anyway it's seems like you have to try uninstall reinstall tensorflow or maybe try it in another version.

**Comment by Estebandobrasil** [comment]
Thank you for your answer. Here is a summary of my environment:
Windows 10
Tensorflow 1.15 - Indeed with version 2.* I had problems with tf.contrib.slim, which seems to be TensorFlow 1.15 code 
Python 3.7 
Cuda 10.0
There seems to be a solution to make Open Pose work with Tensorflow 2* : migrating the code to solve the tf.contrib.slim issue. It is explained here: https://www.tensorflow.org/guide/migrate#a_note_on_slim_contriblayers
Would you recommand applying this migration? Thanks

**Comment by elbekri** [comment]
> Thank you for your answer. Here is a summary of my environment:
> Windows 10
> Tensorflow 1.15 - Indeed with version 2.* I had problems with tf.contrib.slim, which seems to be TensorFlow 1.15 code
> Python 3.7
> Cuda 10.0
> There seems to be a solution to make Open Pose work with Tensorflow 2* : migrating the code to solve the tf.contrib.slim issue. It is explained here: https://www.tensorflow.org/guide/migrate#a_note_on_slim_contriblayers
> Would you recommand applying this migration? Thanks

You can try it of course, i don't remember which version of which lib i used when i posted that code so i can't tell you. But migration to tensorflow 2 can be usefull even if you will probably have to face more issue than it seems. Good luck
