### ISSUE TITLE
NameError: name 'ModuleNotFoundError' is not defined

### ISSUE THREAD

**Issue by Anitkrun** [ildoonet/tf-pose-estimation#274]
I seem to be getting this error.

`Traceback (most recent call last):
  File "run.py", line 6, in <module>
    from tf_pose import common
  File "/home/ankit/pose/tf-openpose/tf_pose/__init__.py", line 5, in <module>
    from tf_pose.runner import infer, Estimator, get_estimator
  File "/home/ankit/pose/tf-openpose/tf_pose/runner.py", line 8, in <module>
    from tf_pose.estimator import TfPoseEstimator
  File "/home/ankit/pose/tf-openpose/tf_pose/estimator.py", line 17, in <module>
    except ModuleNotFoundError as e:
NameError: name 'ModuleNotFoundError' is not defined
`
- I have compiled swig.

**Comment by Anitkrun** [comment]
running it with python3 solves the problem. I had set the PYTHONPATH as specified in #196 but could not get it to work.

Running with python2 on my machine gives the above error.
