### ISSUE TITLE
Training fails to start because of pickle error

### ISSUE THREAD

**Issue by izaakvc** [ildoonet/tf-pose-estimation#29]
When I start a simple test training, it throws an error right away:

`(openpose) C:\Users\Op3Mech\tf-openpose>python train.py --model=mobilenet --datapath=lmdb_trainVal --modelpath=models/traintest --logpath=models/traintest/log
[32m[1211 15:18:38 @prefetch.py:170][0m [PrefetchData] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
Traceback (most recent call last):
  File "train.py", line 56, in <module>
    df = get_dataflow_batch(args.datapath, True, args.batchsize)
  File "C:\Users\Op3Mech\tf-openpose\pose_dataset.py", line 338, in get_dataflow_batch
    ds = get_dataflow(path, is_train)
  File "C:\Users\Op3Mech\tf-openpose\pose_dataset.py", line 332, in get_dataflow
    ds = PrefetchData(ds, 1000, multiprocessing.cpu_count())
  File "C:\Users\Op3Mech\AppData\Local\conda\conda\envs\openpose\lib\site-packages\tensorpack\dataflow\prefetch.py", line 177, in __init__
    start_proc_mask_signal(self.procs)
  File "C:\Users\Op3Mech\AppData\Local\conda\conda\envs\openpose\lib\site-packages\tensorpack\utils\concurrency.py", line 212, in start_proc_mask_signal
    p.start()
  File "C:\Users\Op3Mech\AppData\Local\conda\conda\envs\openpose\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\Op3Mech\AppData\Local\conda\conda\envs\openpose\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Op3Mech\AppData\Local\conda\conda\envs\openpose\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Op3Mech\AppData\Local\conda\conda\envs\openpose\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Op3Mech\AppData\Local\conda\conda\envs\openpose\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle Environment objects`

It seems that there is a problem with the fork in Tensorpack?
I tried to use other versions of Tensorpack (like 0.5, 0.6, 0.7.1, 0.8) but all gave this error.

(Using Windows 10, Conda 4.3.30, Python 3.6.3, tensorflow-gpu 1.3.0, tensorpack 0.8.0)

**Comment by tnosho** [comment]
I have the same problem, and I found a issue in tensorpack.
See [Doesn't work in Windows](https://github.com/ppwwyyxx/tensorpack/issues/100) and [this line](https://github.com/ppwwyyxx/tensorpack/blob/2b2e12ed23befc9af23fc022158cec984f6c8243/tensorpack/dataflow/prefetch.py#L71)

**Comment by ildoonet** [comment]
I guess this is the problem for tensorpack. Codes work fine on ubuntu.
