### ISSUE TITLE
google.protobuf.message.DecodeError: Error parsing message

### ISSUE THREAD

**Issue by Kingbadger3d** [ildoonet/tf-pose-estimation#309]
Hi, Can someone explain whats the issue here:
>>> import tf_pose
>>> tf_pose.infer(image="./images/p1.jpg")
[2018-08-30 14:00:23,539] [TfPoseEstimator] [INFO] loading graph from /home/admin78/Desktop/tf-openpose/models/graph/cmu/graph_opt.pb(default size=432x368)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/admin78/Desktop/tf-openpose/tf_pose/runner.py", line 35, in infer
    e = TfPoseEstimator(get_graph_path(model), target_size=(432, 368))
  File "/home/admin78/Desktop/tf-openpose/tf_pose/estimator.py", line 310, in __init__
    graph_def.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message

I also get this error when try the webcam demo:

python run_webcam.py --model=mobilenet_thin_432x368 --camera=0
Traceback (most recent call last):
  File "run_webcam.py", line 36, in <module>
    logger.debug('initialization %s : %s' % (args.model, get_graph_path(args.model)))
  File "/home/admin78/Desktop/tf-openpose/tf_pose/networks.py", line 89, in get_graph_path
    graph_path = os.path.join(base_data_dir, dyn_graph_path[model_name])
KeyError: 'mobilenet_thin_432x368'

Cheers J

**Comment by SonyPony** [comment]
Hi,

I have exactly the same problem. Did you figured it out?

**Comment by taizhehui** [comment]
Hi, I have the same problem. Did you solve it? Thanks.
