### ISSUE TITLE
The model learned by mobilenet_thin only detects the head

### ISSUE THREAD

**Issue by toshiy104** [ildoonet/tf-pose-estimation#318]
@ildoonet 

Hi, I've learned the model with mobilenet_thin.
The commands are as follows.

python3 tf_pose/train.py --model=mobilenet_thin --datapath=../coco/annotations --imgpath=../coco/ --batchsize=16 --lr=0.0001 --modelpath=../model/ --logpath=../log/

I used train2017.zip, val2017.zip, annotations_trainval2017.zip for the coco dataset.
Executing the above command seems to load pretarined waits (model / pretrained / mobilenet_v1_0.75_224_2017_06_14 / mobilenet_v1_0.75_224.ckpt).

After learning about 200,000 times, I've converted model-200000 to graph.pb and detected skeleton with run.py. And I got the following results.

![tf-openpose-learning-mobilenet_thin](https://user-images.githubusercontent.com/1628377/45066094-9bacbd80-b0f7-11e8-8538-44819715b798.jpg)

As you can see from the results above, the learned model could only be detected from the head to the shoulder. Increasing the number of learning did not change the result much.

How can I get the correct results?
Is the dataset wrong?
Or are pretrained waits wrong?

**Comment by toshiy104** [comment]
Was self resolved.

I changed the learning rate from 0.0001 to 0.01,
then the whole body heat map can now be detected.

**Comment by ariel415el** [comment]
Hi, 
I have the exact same problem as you had.  My trained model (on COCO2017) detects only the head kps

As you suggested I tried starting with **lr=0.01** but it didn't help.
I also read here that @ildoonet  trained with batch size 256 so I implemented a virtual batch in order to use the same batch-size (I have only one 1080Ti) but that didn't help neither

All my training on the COCO dataset converged very quickly (after less than 10k steps) but the main loss stands on ~400 and so is the validation loss and since you said yours didn't converge untill 200,000 steps I suspect I have a bug somwhere

Can you share the training parameter you used and describe the training session (may be share the loss graph)

Thanks,
Ariel.

**Comment by ariel415el** [comment]
Hi,
I think I solved this:

I think there is a bug in the **run_checkpoint.py** 
The scripts creates a **.pbtxt** file with the graph definition in a non trainable state which doesn't allow the **freeze_graph.py** script to load the checkpoints weights into the variables:

**fix:**
#net, _, last_layer = get_network(args.model, input_node, sess, trainable=False)
net, _, last_layer = get_network(args.model, input_node, sess, trainable=True)
in
https://github.com/ildoonet/tf-pose-estimation/blob/dbc89c7c7efdf5aaf56b3bb0f53ef32ea3eaff76/run_checkpoint.py#L27

worked for me..

**Comment by chrisskab** [comment]
Have you figured it out ?

**Comment by ariel415el** [comment]
> Have you figured it out ?

HI, 
what do you mean?

**Comment by chrisskab** [comment]
@ariel415el  I am in the same situation: my loss also converges at 400 after 10k iterations and my model only detects the head. Did you figure out a way to fix this ?

**Comment by weilanShi** [comment]
> @ildoonet
> 
> Hi, I've learned the model with mobilenet_thin.
> The commands are as follows.
> 
> python3 tf_pose/train.py --model=mobilenet_thin --datapath=../coco/annotations --imgpath=../coco/ --batchsize=16 --lr=0.0001 --modelpath=../model/ --logpath=../log/
> 
> I used train2017.zip, val2017.zip, annotations_trainval2017.zip for the coco dataset.
> Executing the above command seems to load pretarined waits (model / pretrained / mobilenet_v1_0.75_224_2017_06_14 / mobilenet_v1_0.75_224.ckpt).
> 
> After learning about 200,000 times, I've converted model-200000 to graph.pb and detected skeleton with run.py. And I got the following results.
> 
> ![tf-openpose-learning-mobilenet_thin](https://user-images.githubusercontent.com/1628377/45066094-9bacbd80-b0f7-11e8-8538-44819715b798.jpg)
> 
> As you can see from the results above, the learned model could only be detected from the head to the shoulder. Increasing the number of learning did not change the result much.
> 
> How can I get the correct results?
> Is the dataset wrong?
> Or are pretrained waits wrong?



How did you convert CKPT to PB model? The PB model I transferred out cannot be tested. Here is my conversion code:

import tensorflow as tf
#from create_tf_record import *
from tensorflow.python.framework import graph_util

def freeze_graph(input_checkpoint,output_graph):
    output_node_names = "Openpose/concat_stage7"
    saver = tf.train.import_meta_graph(input_checkpoint + '.meta', clear_devices=True)
    graph = tf.get_default_graph() # 获得默认的图
    input_graph_def = graph.as_graph_def()  # 返回一个序列化的图代表当前的图
 
    with tf.Session() as sess:
        saver.restore(sess, input_checkpoint) #恢复图并得到数据
        output_graph_def = graph_util.convert_variables_to_constants(  # 模型持久化，将变量值固定
            sess=sess,
            input_graph_def=input_graph_def,# 等于:sess.graph_def
            output_node_names=output_node_names.split(','))# 如果有多个输出节点，以逗号隔开
 
        with tf.gfile.GFile(output_graph, "wb") as f: #保存模型
            f.write(output_graph_def.SerializeToString()) #序列化输出
        print("%d ops in the final graph." % len(output_graph_def.node)) #得到当前图有几个操作节点

input_checkpoint = "./ckpt/model_latest-20000"
out_pb_path='pb_pre.pb'
freeze_graph(input_checkpoint, out_pb_path)

![Screenshot from 2020-11-18 09-14-41](https://user-images.githubusercontent.com/37575293/99477539-a9278880-298d-11eb-8b83-1b0bdb8be0b0.png)

the first node name of pb model is fifo_queue( type: FIFOQueueV2) ,and the shapes: [1,368,432,3], [1,46,54,19], [1,46,54,38], the output node name is fifo_queue

**Comment by yirenpingsheng** [comment]
Hi, guys. Did you tried another mobilenet model, such as mobilenet, mobilenet_fast, mobilenet_accurate? When I training these models, I got some errors. It's relate to the moiblenet framework, especially the dimension of loss. However, mobilenet_thin is ok.
Could you help me? And the screenshot of the error is attached. Thanks a lot.

My system is Ubuntu 16.04. GPU is Titan XP and gtx 1080. The batchsize is 16.



(tf_openpose) atis@atis-S2400GP:~/Project/tf-pose-estimation-master$ python train.py --model mobilenet --datapath /media/atis/_disk3/COCO/annotations --imgpath /media/atis/_disk3/COCO//home/atis/miniconda3/envs/tf_openpose/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/atis/miniconda3/envs/tf_openpose/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/atis/miniconda3/envs/tf_openpose/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/atis/miniconda3/envs/tf_openpose/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/atis/miniconda3/envs/tf_openpose/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/atis/miniconda3/envs/tf_openpose/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
2020-11-26 11:43:49.791872: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1895370000 Hz
2020-11-26 11:43:49.793465: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55be3a630060 executing computations on platform Host. Devices:
2020-11-26 11:43:49.793528: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2020-11-26 11:43:49.928446: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.911
pciBusID: 0000:03:00.0
totalMemory: 7.92GiB freeMemory: 7.53GiB
2020-11-26 11:43:49.928515: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2020-11-26 11:43:49.929601: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-11-26 11:43:49.929630: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2020-11-26 11:43:49.929645: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2020-11-26 11:43:49.929770: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7322 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:03:00.0, compute capability: 6.1)
2020-11-26 11:43:49.932512: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55be3ad26780 executing computations on platform CUDA. Devices:
2020-11-26 11:43:49.932555: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce GTX 1080, Compute Capability 6.1
[2020-11-26 11:43:51,980] [train] [INFO] define model+
2020-11-26 11:43:51,980 INFO define model+
[2020-11-26 11:43:51,984] [pose_dataset] [INFO] dataflow img_path=/media/atis/_disk3/COCO/
2020-11-26 11:43:51,984 INFO dataflow img_path=/media/atis/_disk3/COCO/
loading annotations into memory...
Done (t=10.39s)
creating index...
index created!
[2020-11-26 11:44:03,436] [pose_dataset] [INFO] /media/atis/_disk3/COCO/annotations dataset 118287
2020-11-26 11:44:03,436 INFO /media/atis/_disk3/COCO/annotations dataset 118287
[1126 11:44:03 @parallel.py:219] [MultiProcessRunner] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
[1126 11:44:03 @argtools.py:138] WRN Starting a process with 'fork' method is not safe and may consume unnecessary extra CPU memory. Use 'forkserver' or 'spawn' method (available after Py3.4) instead if you run into any issues. See https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods on how to set them.
[1126 11:44:03 @argtools.py:138] WRN "import prctl" failed! Install python-prctl so that processes can be cleaned with guarantee.
[2020-11-26 11:44:04,012] [pose_dataset] [INFO] dataflow img_path=/media/atis/_disk3/COCO/
2020-11-26 11:44:04,012 INFO dataflow img_path=/media/atis/_disk3/COCO/
loading annotations into memory...
Done (t=0.63s)
creating index...
index created!
[2020-11-26 11:44:04,698] [pose_dataset] [INFO] /media/atis/_disk3/COCO/annotations dataset 5000
2020-11-26 11:44:04,698 INFO /media/atis/_disk3/COCO/annotations dataset 5000
[1126 11:44:04 @parallel.py:219] [MultiProcessRunner] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
[1126 11:44:04 @argtools.py:138] WRN "import prctl" failed! Install python-prctl so that processes can be cleaned with guarantee.
[2020-11-26 11:44:05,501] [train] [DEBUG] tensorboard val image: 12
2020-11-26 11:44:05,501 DEBUG tensorboard val image: 12
[2020-11-26 11:44:05,502] [train] [DEBUG] Tensor("fifo_queue_Dequeue:0", shape=(8, 368, 432, 3), dtype=float32, device=/device:CPU:*)
2020-11-26 11:44:05,502 DEBUG Tensor("fifo_queue_Dequeue:0", shape=(8, 368, 432, 3), dtype=float32, device=/device:CPU:*)
[2020-11-26 11:44:05,535] [train] [DEBUG] Tensor("fifo_queue_Dequeue:1", shape=(8, 46, 54, 19), dtype=float32, device=/device:CPU:*)
2020-11-26 11:44:05,535 DEBUG Tensor("fifo_queue_Dequeue:1", shape=(8, 46, 54, 19), dtype=float32, device=/device:CPU:*)
[2020-11-26 11:44:05,536] [train] [DEBUG] Tensor("fifo_queue_Dequeue:2", shape=(8, 46, 54, 38), dtype=float32, device=/device:CPU:*)
2020-11-26 11:44:05,536 DEBUG Tensor("fifo_queue_Dequeue:2", shape=(8, 46, 54, 38), dtype=float32, device=/device:CPU:*)
num of gpus 1
************************************q_inp Tensor("fifo_queue_Dequeue:0", shape=(8, 368, 432, 3), dtype=float32, device=/device:CPU:*)
+++++++++++++++++++++++++++++++++++++++q_heat Tensor("fifo_queue_Dequeue:1", shape=(8, 46, 54, 19), dtype=float32, device=/device:CPU:*)
------------------------------------q_vect Tensor("fifo_queue_Dequeue:2", shape=(8, 46, 54, 38), dtype=float32, device=/device:CPU:*)
************************************q_inp_split [<tf.Tensor 'split:0' shape=(8, 368, 432, 3) dtype=float32>]
+++++++++++++++++++++++++++++++++++++++q_heat_split [<tf.Tensor 'split_1:0' shape=(8, 46, 54, 19) dtype=float32>]
------------------------------------q_vect_split [<tf.Tensor 'split_2:0' shape=(8, 46, 54, 38) dtype=float32>]
************************************l1 Tensor("Openpose/MConv_Stage1_L1_5_pointwise/BatchNorm/FusedBatchNorm:0", shape=(8, 92, 108, 38), dtype=float32, device=/device:GPU:0)
+++++++++++++++++++++++++++++++++++++++l2 Tensor("Openpose/MConv_Stage1_L2_5_pointwise/BatchNorm/FusedBatchNorm:0", shape=(8, 92, 108, 19), dtype=float32, device=/device:GPU:0)
------------------------------------output_vectmap [<tf.Tensor 'Openpose/MConv_Stage5_L1_5_pointwise/BatchNorm/FusedBatchNorm:0' shape=(8, 92, 108, 38) dtype=float32>]
------------------------------------output_heatmap [<tf.Tensor 'Openpose/MConv_Stage5_L2_5_pointwise/BatchNorm/FusedBatchNorm:0' shape=(8, 92, 108, 19) dtype=float32>]
Traceback (most recent call last):
  File "/home/atis/miniconda3/envs/tf_openpose/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1659, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 92 and 46 for 'sub' (op: 'Sub') with input shapes: [8,92,108,38], [8,46,54,38].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 123, in <module>
    loss_l1 = tf.nn.l2_loss(tf.concat(l1, axis=0) - q_vect_split[gpu_id], name='loss_l1_stage%d_tower%d' % (idx, gpu_id))
  File "/home/atis/miniconda3/envs/tf_openpose/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py", line 812, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/atis/miniconda3/envs/tf_openpose/lib/python3.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 9536, in sub
    "Sub", x=x, y=y, name=name)
  File "/home/atis/miniconda3/envs/tf_openpose/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/atis/miniconda3/envs/tf_openpose/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/atis/miniconda3/envs/tf_openpose/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/atis/miniconda3/envs/tf_openpose/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1823, in __init__
    control_input_ops)
  File "/home/atis/miniconda3/envs/tf_openpose/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1662, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 92 and 46 for 'sub' (op: 'Sub') with input shapes: [8,92,108,38], [8,46,54,38].
