### ISSUE TITLE
train error on win 10

### ISSUE THREAD

**Issue by binhmuc** [ildoonet/tf-pose-estimation#320]
I try to train but got error:
My log:

> define model+
[2018-09-07 11:21:27,056] [pose_dataset] [INFO] dataflow img_path=./data/val2017/
loading annotations into memory...
Done (t=0.31s)
creating index...
index created!
[2018-09-07 11:21:27,384] [pose_dataset] [INFO] ./data/annotations_trainval2017/annotations/ dataset 5000
[32m[0907 11:21:27 @parallel.py:175][0m [5m[31mWRN[0m MultiProcessPrefetchData does support windows. However, windows requires more strict picklability on processes, which may lead of failure on some of the code.
[32m[0907 11:21:27 @parallel.py:185][0m [MultiProcessPrefetchData] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.

After that, for a long time. I cannot see anything...My machine is win 10 64bit. Python 3.5.2, tensorflow is 1.8

**Comment by binhmuc** [comment]
Wait for a long time and i got log:

> Traceback (most recent call last):
  File "C:\Users\PC'\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\platform\self_check.py", line 87, in preload_check
    ctypes.WinDLL(build_info.cudnn_dll_name)
  File "C:\Users\PC'\AppData\Local\Programs\Python\Python35\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 1455] The paging file is too small for this operation to complete

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\PC'\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\PC'\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 115, in _main
    prepare(preparation_data)
  File "C:\Users\PC'\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 226, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\PC'\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 278, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\PC'\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 254, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\PC'\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\PC'\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\tf-openpose\train.py", line 11, in <module>
    import tensorflow as tf
  File "C:\Users\PC'\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\PC'\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\PC'\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "C:\Users\PC'\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\platform\self_check.py", line 97, in preload_check
    % (build_info.cudnn_dll_name, build_info.cudnn_version_number))
ImportError: Could not find 'cudnn64_7.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 7 from this URL: https://developer.nvidia.com/cudnn
Traceback (most recent call last):
  File "train.py", line 70, in <module>
    df = get_dataflow_batch(args.datapath, True, args.batchsize, img_path=args.imgpath)
  File "D:\tf-openpose\tf_pose\pose_dataset.py", line 388, in get_dataflow_batch
    ds = get_dataflow(path, is_train, img_path=img_path)
  File "D:\tf-openpose\tf_pose\pose_dataset.py", line 367, in get_dataflow
    ds = PrefetchData(ds, 1000, multiprocessing.cpu_count() * 4)
  File "C:\Users\PC'\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorpack\dataflow\parallel.py", line 192, in __init__
    start_proc_mask_signal(self.procs)
  File "C:\Users\PC'\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorpack\utils\concurrency.py", line 234, in start_proc_mask_signal
    p.start()
  File "C:\Users\PC'\AppData\Local\Programs\Python\Python35\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\PC'\AppData\Local\Programs\Python\Python35\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\PC'\AppData\Local\Programs\Python\Python35\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Users\PC'\AppData\Local\Programs\Python\Python35\lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\PC'\AppData\Local\Programs\Python\Python35\lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe

Maybe due to memory. I have 8G ram. I make sure i install cudnn64_7.dll carefully

**Comment by arnitkun** [comment]
> OSError: [WinError 1455] The paging file is too small for this operation to complete

Actually it says the paging file is small.  Try increasing it to 1.5 times your ram, if it isn't already.

**Comment by lowkick** [comment]
Same here, solved by reducing the number of threads. In pose_dataset.py, line 444, you see

ds = PrefetchData(ds, 1000, multiprocessing.cpu_count() * 4)

This spawns 32 threads (on my cpu) and each one is trying to allocate 4GB. Maybe it depends on windows implementation of parallelprocessomething, who knows. Anyway reducing it to 

ds = PrefetchData(ds, 1000, 2)

solved the problem.

But, still, with windows training won't start, giving a nice

[ERROR] err type2, err=Cannot feed value of shape (1, 184, 184, 19) for Tensor 'heatmap:0', which has shape '(1, 46, 46, 19)', placeholders=[<tf.Tensor 'image:0' shape=(1, 368, 368, 3) dtype=float32>, <tf.Tensor 'heatmap:0' shape=(1, 46, 46, 19) dtype=float32>, <tf.Tensor 'vectmap:0' shape=(1, 46, 46, 38) dtype=float32>]

**Comment by chrisskab** [comment]
@lowkick Could you manage to train the model with a 16GB RAM ?

**Comment by binhmuc** [comment]
I solved with new graphic card. Titan X saves my life.

**Comment by freedanfan** [comment]
@lowkick It works. thank you.
