### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by Jalpa119** [ildoonet/tf-pose-estimation#323]
Hi, I am trying to start training but after every 100 steps, I am getting this error. 

```
Traceback (most recent call last):
  File "train.py", line 334, in <module>
[2018-09-14 18:09:16,836] [pose_dataset] [ERROR] err type1, placeholders=[<tf.Tensor 'image:0' shape=(4, 368, 368, 3) dtype=float32>, <tf.Tensor 'heatmap:0' shape=(4, 92, 92, 8) dtype=float32>, <tf.Tensor 'vectmap:0' shape=(4, 92, 92, 16) dtype=float32>]
[2018-09-14 18:09:16,836] [pose_dataset] [INFO] Thread-1 Exited.
    test_result = CocoPose.display_image(val_image[i], heatMat[i], pafMat[i], as_numpy=True)
IndexError: index 4 is out of bounds for axis 0 with size 4```

thanks in advance!

**Comment by quchang3** [comment]
did you solve it??

**Comment by Jalpa119** [comment]
No, Still stuck on this.

**Comment by DANNALI35** [comment]
i encountered a similar error here, got no idea.
`
[2018-10-18 10:53:51,738] [pose_dataset] [ERROR] err type1, placeholders=[<tf.Tensor 'image:0' shape=(1, 368, 368, 3) dtype=float32>, <tf.Tensor 'heatmap:0' shape=(1, 92, 92, 19) dtype=float32>, <tf.Tensor 'vectmap:0' shape=(1, 92, 92, 38) dtype=float32>]
[2018-10-18 10:53:51,738] [pose_dataset] [INFO] Thread-1 Exited.
    sample_image = [enqueuer.last_dp[0][i] for i in range(4)]
  File "./tf_pose/train.py", line 251, in <listcomp>
    sample_image = [enqueuer.last_dp[0][i] for i in range(4)]
IndexError: index 1 is out of bounds for axis 0 with size 1
`

**Comment by Gouiaa** [comment]
@Jalpa119  Any solution ? I got the same error. Thanks

**Comment by chrisskab** [comment]
Anyone ?

**Comment by Gouiaa** [comment]
see that https://github.com/ildoonet/tf-pose-estimation/issues/174
