### ISSUE TITLE
video

### ISSUE THREAD

**Issue by shahzadmoghimifar** [ildoonet/tf-pose-estimation#332]
hello every body
how we can run for video?

**Comment by shahzadmoghimifar** [comment]
> can you please tell me how to run run_video.py file? What is the command?

I use "python run_video.py --video=/hddext/shahzad/mel.mp4 --resolution=432x368 --model=mobilenet_thin --cvShowImage=showBG" command for run on video but I receive error as you can see :"usage: run_video.py [-h] [--video VIDEO] [--resolution RESOLUTION]
[--model MODEL] [--show-process SHOW_PROCESS]
[--showBG SHOWBG]
run_video.py: error: unrecognized arguments: --cvShowImage=showBG"
How do I solve it?

**Comment by shahzadmoghimifar** [comment]
> python run_video.py --model=mobilenet_thin --resolution=432x368 --video=./video/1.mp4

thank you for your response, I use your command but I receive this commands as you can see: 

[2018-10-27 12:09:47,989] [TfPoseEstimator-Video] [DEBUG] initialization mobilenet_thin : /hddext/shahzad/tf-pose-estimation-master/models/graph/mobilenet_thin/graph_opt.pb
[2018-10-27 12:09:47,989] [TfPoseEstimator] [INFO] loading graph from /hddext/shahzad/tf-pose-estimation-master/models/graph/mobilenet_thin/graph_opt.pb(default size=432x368)
2018-10-27 12:09:48.064026: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Error opening video stream or file
Traceback (most recent call last):
  File "run_video.py", line 53, in <module>
    cv2.destroyAllWindows()
cv2.error: OpenCV(3.4.2) /tmp/build/80754af9/opencv-suite_1535558553474/work/modules/highgui/src/window.cpp:626: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvDestroyAllWindows'

**Comment by JARVVVIS** [comment]
> > python run_video.py --model=mobilenet_thin --resolution=432x368 --video=./video/1.mp4
> 
> thank you for your response, I use your command but I receive this commands as you can see:
> 
> [2018-10-27 12:09:47,989] [TfPoseEstimator-Video] [DEBUG] initialization mobilenet_thin : /hddext/shahzad/tf-pose-estimation-master/models/graph/mobilenet_thin/graph_opt.pb
> [2018-10-27 12:09:47,989] [TfPoseEstimator] [INFO] loading graph from /hddext/shahzad/tf-pose-estimation-master/models/graph/mobilenet_thin/graph_opt.pb(default size=432x368)
> 2018-10-27 12:09:48.064026: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> Error opening video stream or file
> Traceback (most recent call last):
> File "run_video.py", line 53, in 
> cv2.destroyAllWindows()
> cv2.error: OpenCV(3.4.2) /tmp/build/80754af9/opencv-suite_1535558553474/work/modules/highgui/src/window.cpp:626: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvDestroyAllWindows'

just check once the path that u have included is right or not(./video/1.mp4)
