### ISSUE TITLE
Key Openpose/MConv_Stage6_L2_5_pointwise/weights not found in checkpoint

### ISSUE THREAD

**Issue by sunnyheart008205** [ildoonet/tf-pose-estimation#34]
Hello, does anybody have this problem below? And how to fix this? Thanks very much!

INFO:tensorflow:Restoring parameters from ./models/pretrained/mobilenet_v1_0.75_224_2017_06_14/mobilenet_v1_0.75_224.ckpt
2017-12-27 07:08:31,280 INFO Restoring parameters from ./models/pretrained/mobilenet_v1_0.75_224_2017_06_14/mobilenet_v1_0.75_224.ckpt
2017-12-27 07:08:35.788513: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key Openpose/MConv_Stage6_L2_5_pointwise/weights not found in checkpoint
2017-12-27 07:08:35.789040: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key Openpose/MConv_Stage6_L2_5_pointwise/weights not found in checkpoint
	 [[Node: save/RestoreV2_358 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_358/tensor_names, save/RestoreV2_358/shape_and_slices)]]
2017-12-27 07:08:35.792135: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key Openpose/MConv_Stage6_L2_5_pointwise/weights not found in checkpoint
	 [[Node: save/RestoreV2_358 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_358/tensor_names, save/RestoreV2_358/shape_and_slices)]]
......
2017-12-27 07:08:36.456121: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key Openpose/MConv_Stage6_L1_3_pointwise/BatchNorm/moving_mean not found in checkpoint
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Key Openpose/MConv_Stage6_L2_5_pointwise/weights not found in checkpoint
	 [[Node: save/RestoreV2_358 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_358/tensor_names, save/RestoreV2_358/shape_and_slices)]]
	 [[Node: save/RestoreV2_38/_667 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_1388_save/RestoreV2_38", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference.py", line 36, in <module>
    net, _, last_layer = get_network(args.model, input_node, sess)
  File "/workspace/share/poseestimation/tf-pose-estimation/networks.py", line 49, in get_network
    loader.restore(sess_for_load, os.path.join(_get_base_path(), ckpts[type]))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1560, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key Openpose/MConv_Stage6_L2_5_pointwise/weights not found in checkpoint
	 [[Node: save/RestoreV2_358 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_358/tensor_names, save/RestoreV2_358/shape_and_slices)]]
	 [[Node: save/RestoreV2_38/_667 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_1388_save/RestoreV2_38", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op 'save/RestoreV2_358', defined at:
  File "inference.py", line 36, in <module>
    net, _, last_layer = get_network(args.model, input_node, sess)
  File "/workspace/share/poseestimation/tf-pose-estimation/networks.py", line 48, in get_network
    loader = tf.train.Saver()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1140, in __init__
    self.build()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1172, in build
    filename=self._filename)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 688, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 663, in restore_v2
    dtypes=dtypes, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Key Openpose/MConv_Stage6_L2_5_pointwise/weights not found in checkpoint
	 [[Node: save/RestoreV2_358 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_358/tensor_names, save/RestoreV2_358/shape_and_slices)]]
	 [[Node: save/RestoreV2_38/_667 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_1388_save/RestoreV2_38", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

**Comment by luohuan2uestc** [comment]
#23 maybe help you。

**Comment by ildoonet** [comment]
#23 is the same. I'm closing this.

Also, I will provide freezed graph file so that developers can enjoy with less effort.

Thanks.
