### ISSUE TITLE
NameError: name 'warnings' is not defined

### ISSUE THREAD

**Issue by shadowdk3** [ildoonet/tf-pose-estimation#347]
When I install tfpose in TX2, I found `NameError: name 'warnings' is not defined.`

here is the log:
```
Installed /usr/local/lib/python3.5/dist-packages/tf_pose-0.1.1-py3.5-linux-aarch64.egg
Processing dependencies for tf-pose==0.1.1
Searching for PyWavelets>=0.4.0
Reading https://pypi.org/simple/PyWavelets/
Downloading https://files.pythonhosted.org/packages/b4/42/074c6adcd1586926650d8365bcc3e1ab42f81a68c620c4242aa9297b01d9/PyWavelets-1.0.1.tar.gz#sha256=3c5cece36d4e17d395be6e9ac6b80ce7b774a1f71c251756c6163e63b6d878dc
Best match: PyWavelets 1.0.1
Processing PyWavelets-1.0.1.tar.gz
Writing /tmp/easy_install-kwfp0bkm/PyWavelets-1.0.1/setup.cfg
Running PyWavelets-1.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-kwfp0bkm/PyWavelets-1.0.1/egg-dist-tmp-vz8lxh_c
Traceback (most recent call last):
  File "/home/nvidia/.local/lib/python3.5/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/nvidia/.local/lib/python3.5/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/nvidia/.local/lib/python3.5/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/nvidia/.local/lib/python3.5/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-kwfp0bkm/PyWavelets-1.0.1/setup.py", line 453, in <module>
  File "/tmp/easy_install-kwfp0bkm/PyWavelets-1.0.1/setup.py", line 427, in setup_package
  File "/tmp/easy_install-kwfp0bkm/PyWavelets-1.0.1/setup.py", line 359, in parse_setuppy_commands
NameError: name 'warnings' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 66, in <module>
    zip_safe=False)
  File "/home/nvidia/.local/lib/python3.5/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/nvidia/.local/lib/python3.5/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/nvidia/.local/lib/python3.5/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/home/nvidia/.local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 415, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/nvidia/.local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 657, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/nvidia/.local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 704, in install_item
    self.process_distribution(spec, dist, deps)
  File "/home/nvidia/.local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 749, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/home/nvidia/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 777, in resolve
    replace_conflicting=replace_conflicting
  File "/home/nvidia/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1060, in best_match
    return self.obtain(req, installer)
  File "/home/nvidia/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1072, in obtain
    return installer(requirement)
  File "/home/nvidia/.local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 676, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/nvidia/.local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 702, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/nvidia/.local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 887, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/nvidia/.local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1155, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/nvidia/.local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1141, in run_setup
    run_setup(setup_script, args)
  File "/home/nvidia/.local/lib/python3.5/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/nvidia/.local/lib/python3.5/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/nvidia/.local/lib/python3.5/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/home/nvidia/.local/lib/python3.5/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/home/nvidia/.local/lib/python3.5/site-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/nvidia/.local/lib/python3.5/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/nvidia/.local/lib/python3.5/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/nvidia/.local/lib/python3.5/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/nvidia/.local/lib/python3.5/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-kwfp0bkm/PyWavelets-1.0.1/setup.py", line 453, in <module>
  File "/tmp/easy_install-kwfp0bkm/PyWavelets-1.0.1/setup.py", line 427, in setup_package
  File "/tmp/easy_install-kwfp0bkm/PyWavelets-1.0.1/setup.py", line 359, in parse_setuppy_commands
NameError: name 'warnings' is not defined

```

**Comment by shadowdk3** [comment]
downgrade PyWavelets to 0.5.2 and install again.
