### ISSUE TITLE
parse the freeze model or the opt model

### ISSUE THREAD

**Issue by luckhhn** [ildoonet/tf-pose-estimation#388]
parser.add_argument('--model', type=str, default='cmu', help='cmu / mobilenet_thin')

I modified mobilenet_thin to become cmu, I downloaded the bp file, and then reported an error, if convenient, please tell me how to solve, I am new, thank you

error:

Traceback (most recent call last):
  File "H:/tf-pose-estimation-master/run_webcam.py", line 41, in <module>
    e = TfPoseEstimator(get_graph_path(args.model), target_size=(432, 368))
  File "H:\tf-pose-estimation-master\tf_pose\estimator.py", line 310, in __init__
    graph_def.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message

**Comment by Eva-Deng** [comment]
I meet the same problem with you，did you solve it?

**Comment by starry-night-0** [comment]
@luckhhn
Did you solve the problem? Thank you.
