### ISSUE TITLE
Error running pretrained mobile net

### ISSUE THREAD

**Issue by xjoshramos** [ildoonet/tf-pose-estimation#4]
2017-10-13 14:03:26.126089: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key Openpose/MConv_Stage6_L1_3_pointwise/BatchNorm/moving_mean not found in checkpoint
2017-10-13 14:03:26.126193: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key Openpose/MConv_Stage6_L1_3_depthwise/depthwise_weights not found in checkpoint
2017-10-13 14:03:26.126316: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key Openpose/MConv_Stage6_L1_4_depthwise/depthwise_weights not found in checkpoint
2017-10-13 14:03:26.126335: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key Openpose/MConv_Stage6_L1_3_pointwise/weights not found in checkpoint
2017-10-13 14:03:26.126340: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key Openpose/MConv_Stage6_L1_4_pointwise/BatchNorm/beta not found in checkpoint
2017-10-13 14:03:26.126343: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key Openpose/MConv_Stage6_L1_3_pointwise/BatchNorm/beta not found in checkpoint
Traceback (most recent call last):
  File "inference.py", line 54, in <module>
    loader.restore(sess, '/media/joshua/5d133d05-fcd7-4aa1-b351-a386ed74b6b7/tf-openpose/models/pretrained/mobilenet_v1_0.50_224_2017_06_14/mobilenet_v1_0.50_224.ckpt')#'./models/trained/mobilenet_retry/model-100000')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1560, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key Openpose/MConv_Stage6_L2_5_pointwise/weights not found in checkpoint
	 [[Node: save/RestoreV2_358 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_358/tensor_names, save/RestoreV2_358/shape_and_slices)]]
	 [[Node: save/RestoreV2_35/_665 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_1386_save/RestoreV2_35", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'save/RestoreV2_358', defined at:
  File "inference.py", line 53, in <module>
    loader = tf.train.Saver()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1140, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1172, in build
    filename=self._filename)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 688, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 663, in restore_v2
    dtypes=dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Key Openpose/MConv_Stage6_L2_5_pointwise/weights not found in checkpoint
	 [[Node: save/RestoreV2_358 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_358/tensor_names, save/RestoreV2_358/shape_and_slices)]]
	 [[Node: save/RestoreV2_35/_665 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_1386_save/RestoreV2_35", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

**Comment by ildoonet** [comment]
I will share it after I trained it with descent performance.

**Comment by sunnyheart008205** [comment]
@ildoonet  Has this problem been fixed？ I have also met this error, and don't know how to do. Can you help me?

**Comment by ildoonet** [comment]
@sunnyheart008205 @xjoshramos 

This problem is caused because the weight file is missing.

Please download files as described in README. 

Also, I just updated this repo so that you can just run a basic model with tensorflow graph file. 

Please see the updated readme.

**Comment by ildoonet** [comment]
Close due to inactivity.
