### ISSUE TITLE
Loading images error of CMU Training on COCO2017

### ISSUE THREAD

**Issue by erwangccc** [ildoonet/tf-pose-estimation#405]
Hi,guys

I meet this error when I was going to train a cmu model on the coco2017 dataset,do you have any ideas to solve this problem? i would appreciate it if you have advice to share me.

- OS:ubantu16.04
- GPU:TITAN X
- Batchsize:64

```
mask.py err= No module named 'tf_pose.pycocotools._mask'
[2019-02-25 14:37:23,011] [train] [INFO] define model+
loading annotations into memory...
[2019-02-25 14:37:23,015] [pose_dataset] [INFO] dataflow img_path=data/coco_data/
Done (t=7.79s)
creating index...
[2019-02-25 14:37:31,705] [pose_dataset] [INFO] data/coco_data/annotations dataset 118287
index created!
[0225 14:37:31 @parallel.py:195] [MultiProcessPrefetchData] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
[2019-02-25 14:37:31,769] [pose_dataset] [WARNING] image not read, path=data/coco_data/train2017/000000562845.jpg
Process _Worker-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/dataflow/parallel.py", line 171, in run
    for dp in self.ds:
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/dataflow/common.py", line 296, in __iter__
    for dp in self.ds:
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/dataflow/common.py", line 296, in __iter__
    for dp in self.ds:
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/dataflow/common.py", line 296, in __iter__
    for dp in self.ds:
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/dataflow/common.py", line 296, in __iter__
    for dp in self.ds:
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/dataflow/common.py", line 296, in __iter__
    for dp in self.ds:
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/dataflow/common.py", line 296, in __iter__
    for dp in self.ds:
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/dataflow/common.py", line 297, in __iter__
    ret = self.func(copy(dp))  # shallow copy the list
  File "/home/osksh/tf-openpose/tf_pose/pose_dataset.py", line 344, in read_image_url
    raise Exception()
Exception
[2019-02-25 14:37:31,788] [pose_dataset] [WARNING] image not read, path=data/coco_data/train2017/000000129568.jpg
Process _Worker-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/dataflow/parallel.py", line 171, in run
    for dp in self.ds:
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/dataflow/common.py", line 296, in __iter__
    for dp in self.ds:
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/dataflow/common.py", line 296, in __iter__
    for dp in self.ds:
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/dataflow/common.py", line 296, in __iter__
    for dp in self.ds:
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/dataflow/common.py", line 296, in __iter__
    for dp in self.ds:
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/dataflow/common.py", line 296, in __iter__
    for dp in self.ds:
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/dataflow/common.py", line 296, in __iter__
    for dp in self.ds:
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/dataflow/common.py", line 297, in __iter__
    ret = self.func(copy(dp))  # shallow copy the list
  File "/home/osksh/tf-openpose/tf_pose/pose_dataset.py", line 344, in read_image_url
    raise Exception()
Exception
[2019-02-25 14:37:31,803] [pose_dataset] [WARNING] image not read, path=data/coco_data/train2017/000000212054.jpg
```

**Comment by erwangccc** [comment]
Image is EMPTY,it's a careless problem.
Sorry to bother you
