### ISSUE TITLE
AttributeError: 'TfPoseEstimator' object has no attribute 'persistent_sess'

### ISSUE THREAD

**Issue by ustcerman** [ildoonet/tf-pose-estimation#46]
/usr/bin/python3.5 /home/hqt/tf-openpose/src/run.py
/home/hqt/.local/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/home/hqt/tf-openpose/src/run.py", line 32, in <module>
    e = TfPoseEstimator(get_graph_path(args.model), target_size=(w, h))
  File "/home/hqt/tf-openpose/src/estimator.py", line 255, in __init__
    graph_def.ParseFromString(f.read())
  File "/home/hqt/.local/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 119, in read
    self._preread_check()
  File "/home/hqt/.local/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 79, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/home/hqt/.local/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: ./models/graph/mobilenet_thin_432x368/graph_opt.pb; No such file or directory
Exception ignored in: <bound method TfPoseEstimator.__del__ of <estimator.TfPoseEstimator object at 0x7fcdc180e3c8>>
Traceback (most recent call last):
  File "/home/hqt/tf-openpose/src/estimator.py", line 278, in __del__
    self.persistent_sess.close()
AttributeError: 'TfPoseEstimator' object has no attribute 'persistent_sess'

I run the  test the inference feature with a single image. use

$ python3 run.py --model=mobilenet_thin_432x368 --image=
but has a error,Anybody meet this problem?

**Comment by elmuz** [comment]
> tensorflow.python.framework.errors_impl.NotFoundError:
> ./models/graph/mobilenet_thin_432x368/graph_opt.pb; No such file or directory

Try laucnhing the script from the repo root (parent folder)
`$python3 src/run.py --model=mobilenet_thin_432x368 --image=`

**Comment by lesreaper** [comment]
Or you can run it as stated in the ReadMe and use a relative image path "../../Desktop"...

**Comment by pushkalkatara** [comment]
Same issue while using roslauch, please help.

**Comment by Svito-zar** [comment]
@elmuz, your solution helped me, when I used --model=mobilenet_thin_432x368, but I have got the same error again when using any other model, like cmu_640x480 or cmu_640x360.

I am getting the error about  'persistent_sess' for these models also when running src/run.py

**Comment by paperclipt** [comment]
@Svito-zar did you figure out the problem? i got the same error when i use cmu_640x480 or cmu_640x360

**Comment by elmuz** [comment]
@Svito-zar @paperclipt be sure you downloaded the trained model you need.
I pulled this morning the repository and I can confirm it works ok. 'cmu_640x480' and 'cmu_640x360' have to be taken from mediafire links inside download.sh file. If you just execute the .sh file it may not work, try manually download those files through a web browser. After copying those files accordingly in their folders, I can confirm the tool works nicely.

**Comment by paperclipt** [comment]
@Svito-zar @elmuz thanks. after using the files downloaded from the web browser, i confirm that it works.
