### ISSUE TITLE
glibc error

### ISSUE THREAD

**Issue by absagargupta** [ildoonet/tf-pose-estimation#468]
I am training on centos 6.5, python 3.6. It is a server so, I don't have sudo privileges. I am encountering the following gcc error while running the command:- python3 tf_pose/train.py --model=cmu  --batchsize=64 --lr=0.001. I have given the dataset and annotations as defaults in the code. The error is :
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found
(required by /home/sagar18174/tf-pose-estimation/tf_pose/pafprocess/_pafprocess.cpython-37m-x86_64-linux-gnu.so)

The whole log file is:
(pose) [sagar18174@hpc tf-pose-estimation]$ python3 tf_pose/train.py
--model=cmu --batchsize=64 --lr=0.001
Traceback (most recent call last):
  File "tf_pose/train.py", line 14, in <module>
    from pose_dataset import get_dataflow_batch, DataFlowToQueue, CocoPose
  File "/home/sagar18174/tf-pose-estimation/tf_pose/pose_dataset.py",
line 31, in <module>
    from pose_augment import pose_flip, pose_rotation, pose_to_img,
pose_crop_random, \
  File "/home/sagar18174/tf-pose-estimation/tf_pose/pose_augment.py",
line 8, in <module>
    from tf_pose.common import CocoPart
  File "/home/sagar18174/tf-pose-estimation/tf_pose/__init__.py", line
5, in <module>
    from tf_pose.runner import infer, Estimator, get_estimator
  File "/home/sagar18174/tf-pose-estimation/tf_pose/runner.py", line
8, in <module>
    from tf_pose import eval
  File "/home/sagar18174/tf-pose-estimation/tf_pose/eval.py", line 13,
in <module>
    from tf_pose.estimator import TfPoseEstimator
  File "/home/sagar18174/tf-pose-estimation/tf_pose/estimator.py",
line 16, in <module>
    from tf_pose.pafprocess import pafprocess
  File "/home/sagar18174/tf-pose-estimation/tf_pose/pafprocess/pafprocess.py",
line 25, in <module>
    _pafprocess = swig_import_helper()
  File "/home/sagar18174/tf-pose-estimation/tf_pose/pafprocess/pafprocess.py",
line 21, in swig_import_helper
    _mod = imp.load_module('_pafprocess', fp, pathname, description)
  File "/home/sagar18174/.conda/envs/pose/lib/python3.7/imp.py", line
242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/sagar18174/.conda/envs/pose/lib/python3.7/imp.py", line
342, in load_dynamic
    return _load(spec)
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found
(required by /home/sagar18174/tf-pose-estimation/tf_pose/pafprocess/_pafprocess.cpython-37m-x86_64-linux-gnu.so)

generally the glibc error goes away with reinstallation in case of tensorflow and pytorch, but here is re occuring. 
I also checked my system's glibc version by ldd-version and the output is 2.14.

Please advise.

**Comment by absagargupta** [comment]
I solved it. Downgrading the numpy to 1.16.1 and tensorflow to 1.1.0 solved the problem.
