### ISSUE TITLE
   _, gs_num = sess.run([train_op, global_step])  Stop Run！！！

### ISSUE THREAD

**Issue by smisthzhu** [ildoonet/tf-pose-estimation#485]
last_log_epoch1 = last_log_epoch2 = -1
        while True:
            _, gs_num = sess.run([train_op, global_step]) #here
            curr_epoch = float(gs_num) / step_per_epoch
 
 After the execution of this line, the program has not responded, feeling vacation dead, what is the reason? Also, when I executed train.py, I felt that it was cpu, not GPU,   How to set up GPU? thank you!

**Comment by smisthzhu** [comment]
parser = argparse.ArgumentParser(description='Training codes for Openpose using Tensorflow')
    parser.add_argument('--model', default='mobilenet_v2_1.4', help='model name')
    parser.add_argument('--datapath', type=str, default='d:/coco/annotations')
    parser.add_argument('--imgpath', type=str, default='d:/coco/')
    parser.add_argument('--batchsize', type=int, default=64)
    parser.add_argument('--gpus', type=int, default=4)
    parser.add_argument('--max-epoch', type=int, default=10)
    parser.add_argument('--lr', type=str, default='0.001')
    parser.add_argument('--tag', type=str, default='test')
    parser.add_argument('--checkpoint', type=str, default='')

    parser.add_argument('--input-width', type=int, default=432)
    parser.add_argument('--input-height', type=int, default=368)
    parser.add_argument('--quant-delay', type=int, default=-1)
    args = parser.parse_args()

    modelpath = logpath = './models/train/'

**Comment by smisthzhu** [comment]
run log：
D:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
[2019-07-12 10:01:02,043] [train] [INFO] define model+
2019-07-12 10:01:02,043 INFO define model+
[2019-07-12 10:01:16,634] [pose_dataset] [INFO] dataflow img_path=d:/coco/
2019-07-12 10:01:16,634 INFO dataflow img_path=d:/coco/
loading annotations into memory...
Done (t=8.23s)
creating index...
index created!
[2019-07-12 10:01:30,835] [pose_dataset] [INFO] d:/coco/annotations dataset 118287
2019-07-12 10:01:30,835 INFO d:/coco/annotations dataset 118287
[0712 10:01:31 @parallel.py:198] WRN MultiProcessRunner does support Windows. However, Windows requires more strict picklability on processes, which may lead of failure on some of the code.
[0712 10:01:31 @parallel.py:210] [MultiProcessRunner] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.

**Comment by smisthzhu** [comment]
D:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
[2019-07-12 10:01:02,043] [train] [INFO] define model+
2019-07-12 10:01:02,043 INFO define model+
[2019-07-12 10:01:16,634] [pose_dataset] [INFO] dataflow img_path=d:/coco/
2019-07-12 10:01:16,634 INFO dataflow img_path=d:/coco/
loading annotations into memory...
Done (t=8.23s)
creating index...
index created!
[2019-07-12 10:01:30,835] [pose_dataset] [INFO] d:/coco/annotations dataset 118287
2019-07-12 10:01:30,835 INFO d:/coco/annotations dataset 118287
[0712 10:01:31 @parallel.py:198] WRN MultiProcessRunner does support Windows. However, Windows requires more strict picklability on processes, which may lead of failure on some of the code.
[0712 10:01:31 @parallel.py:210] [MultiProcessRunner] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
[2019-07-12 10:02:45,099] [pose_dataset] [INFO] dataflow img_path=d:/coco/
2019-07-12 10:02:45,099 INFO dataflow img_path=d:/coco/
loading annotations into memory...
Done (t=0.78s)
creating index...
index created!
[2019-07-12 10:02:52,134] [pose_dataset] [INFO] d:/coco/annotations dataset 5000
2019-07-12 10:02:52,134 INFO d:/coco/annotations dataset 5000
[0712 10:02:52 @develop.py:99] WRN [Deprecated] MultiThreadMapData(nr_thread) will be deprecated after 01 Jan. Renamed to 'num_thread'
[0712 10:02:52 @parallel.py:198] WRN MultiProcessRunner does support Windows. However, Windows requires more strict picklability on processes, which may lead of failure on some of the code.
[2019-07-12 10:02:57,709] [train] [DEBUG] tensorboard val image: 12
2019-07-12 10:02:57,709 DEBUG tensorboard val image: 12
[2019-07-12 10:02:57,710] [train] [DEBUG] Tensor("fifo_queue_Dequeue:0", shape=(64, 368, 432, 3), dtype=float32, device=/device:CPU:*)
2019-07-12 10:02:57,710 DEBUG Tensor("fifo_queue_Dequeue:0", shape=(64, 368, 432, 3), dtype=float32, device=/device:CPU:*)
[2019-07-12 10:02:57,710] [train] [DEBUG] Tensor("fifo_queue_Dequeue:1", shape=(64, 46, 54, 19), dtype=float32, device=/device:CPU:*)
2019-07-12 10:02:57,710 DEBUG Tensor("fifo_queue_Dequeue:1", shape=(64, 46, 54, 19), dtype=float32, device=/device:CPU:*)
[2019-07-12 10:02:57,711] [train] [DEBUG] Tensor("fifo_queue_Dequeue:2", shape=(64, 46, 54, 38), dtype=float32, device=/device:CPU:*)
2019-07-12 10:02:57,711 DEBUG Tensor("fifo_queue_Dequeue:2", shape=(64, 46, 54, 38), dtype=float32, device=/device:CPU:*)

**Comment by smisthzhu** [comment]
D:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
[2019-07-12 10:01:02,043] [train] [INFO] define model+
2019-07-12 10:01:02,043 INFO define model+
[2019-07-12 10:01:16,634] [pose_dataset] [INFO] dataflow img_path=d:/coco/
2019-07-12 10:01:16,634 INFO dataflow img_path=d:/coco/
loading annotations into memory...
Done (t=8.23s)
creating index...
index created!
[2019-07-12 10:01:30,835] [pose_dataset] [INFO] d:/coco/annotations dataset 118287
2019-07-12 10:01:30,835 INFO d:/coco/annotations dataset 118287
[0712 10:01:31 @parallel.py:198] WRN MultiProcessRunner does support Windows. However, Windows requires more strict picklability on processes, which may lead of failure on some of the code.
[0712 10:01:31 @parallel.py:210] [MultiProcessRunner] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
[2019-07-12 10:02:45,099] [pose_dataset] [INFO] dataflow img_path=d:/coco/
2019-07-12 10:02:45,099 INFO dataflow img_path=d:/coco/
loading annotations into memory...
Done (t=0.78s)
creating index...
index created!
[2019-07-12 10:02:52,134] [pose_dataset] [INFO] d:/coco/annotations dataset 5000
2019-07-12 10:02:52,134 INFO d:/coco/annotations dataset 5000
[0712 10:02:52 @develop.py:99] WRN [Deprecated] MultiThreadMapData(nr_thread) will be deprecated after 01 Jan. Renamed to 'num_thread'
[0712 10:02:52 @parallel.py:198] WRN MultiProcessRunner does support Windows. However, Windows requires more strict picklability on processes, which may lead of failure on some of the code.
[2019-07-12 10:02:57,709] [train] [DEBUG] tensorboard val image: 12
2019-07-12 10:02:57,709 DEBUG tensorboard val image: 12
[2019-07-12 10:02:57,710] [train] [DEBUG] Tensor("fifo_queue_Dequeue:0", shape=(64, 368, 432, 3), dtype=float32, device=/device:CPU:*)
2019-07-12 10:02:57,710 DEBUG Tensor("fifo_queue_Dequeue:0", shape=(64, 368, 432, 3), dtype=float32, device=/device:CPU:*)
[2019-07-12 10:02:57,710] [train] [DEBUG] Tensor("fifo_queue_Dequeue:1", shape=(64, 46, 54, 19), dtype=float32, device=/device:CPU:*)
2019-07-12 10:02:57,710 DEBUG Tensor("fifo_queue_Dequeue:1", shape=(64, 46, 54, 19), dtype=float32, device=/device:CPU:*)
[2019-07-12 10:02:57,711] [train] [DEBUG] Tensor("fifo_queue_Dequeue:2", shape=(64, 46, 54, 38), dtype=float32, device=/device:CPU:*)
2019-07-12 10:02:57,711 DEBUG Tensor("fifo_queue_Dequeue:2", shape=(64, 46, 54, 38), dtype=float32, device=/device:CPU:*)
[2019-07-12 10:04:40,278] [train] [INFO] define model-
2019-07-12 10:04:40,278 INFO define model-
INFO:tensorflow:Summary name training sample is illegal; using training_sample instead.
2019-07-12 10:05:05,568 INFO Summary name training sample is illegal; using training_sample instead.
INFO:tensorflow:Summary name validation sample is illegal; using validation_sample instead.
2019-07-12 10:05:05,571 INFO Summary name validation sample is illegal; using validation_sample instead.

**Comment by smisthzhu** [comment]
[2019-07-12 10:05:44,186] [train] [INFO] model weights initialization
2019-07-12 10:05:44,186 INFO model weights initialization
[2019-07-12 10:06:16,156] [train] [INFO] Restore pretrained weights... ./models\pretrained/mobilenet_v2_1.4_224/mobilenet_v2_1.4_224.ckpt
2019-07-12 10:06:16,156 INFO Restore pretrained weights... ./models\pretrained/mobilenet_v2_1.4_224/mobilenet_v2_1.4_224.ckpt
INFO:tensorflow:Restoring parameters from ./models\pretrained/mobilenet_v2_1.4_224/mobilenet_v2_1.4_224.ckpt

**Comment by smisthzhu** [comment]
D:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
[2019-07-12 10:01:02,043] [train] [INFO] define model+
2019-07-12 10:01:02,043 INFO define model+
[2019-07-12 10:01:16,634] [pose_dataset] [INFO] dataflow img_path=d:/coco/
2019-07-12 10:01:16,634 INFO dataflow img_path=d:/coco/
loading annotations into memory...
Done (t=8.23s)
creating index...
index created!
[2019-07-12 10:01:30,835] [pose_dataset] [INFO] d:/coco/annotations dataset 118287
2019-07-12 10:01:30,835 INFO d:/coco/annotations dataset 118287
[0712 10:01:31 @parallel.py:198] WRN MultiProcessRunner does support Windows. However, Windows requires more strict picklability on processes, which may lead of failure on some of the code.
[0712 10:01:31 @parallel.py:210] [MultiProcessRunner] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
[2019-07-12 10:02:45,099] [pose_dataset] [INFO] dataflow img_path=d:/coco/
2019-07-12 10:02:45,099 INFO dataflow img_path=d:/coco/
loading annotations into memory...
Done (t=0.78s)
creating index...
index created!
[2019-07-12 10:02:52,134] [pose_dataset] [INFO] d:/coco/annotations dataset 5000
2019-07-12 10:02:52,134 INFO d:/coco/annotations dataset 5000
[0712 10:02:52 @develop.py:99] WRN [Deprecated] MultiThreadMapData(nr_thread) will be deprecated after 01 Jan. Renamed to 'num_thread'
[0712 10:02:52 @parallel.py:198] WRN MultiProcessRunner does support Windows. However, Windows requires more strict picklability on processes, which may lead of failure on some of the code.
[2019-07-12 10:02:57,709] [train] [DEBUG] tensorboard val image: 12
2019-07-12 10:02:57,709 DEBUG tensorboard val image: 12
[2019-07-12 10:02:57,710] [train] [DEBUG] Tensor("fifo_queue_Dequeue:0", shape=(64, 368, 432, 3), dtype=float32, device=/device:CPU:*)
2019-07-12 10:02:57,710 DEBUG Tensor("fifo_queue_Dequeue:0", shape=(64, 368, 432, 3), dtype=float32, device=/device:CPU:*)
[2019-07-12 10:02:57,710] [train] [DEBUG] Tensor("fifo_queue_Dequeue:1", shape=(64, 46, 54, 19), dtype=float32, device=/device:CPU:*)
2019-07-12 10:02:57,710 DEBUG Tensor("fifo_queue_Dequeue:1", shape=(64, 46, 54, 19), dtype=float32, device=/device:CPU:*)
[2019-07-12 10:02:57,711] [train] [DEBUG] Tensor("fifo_queue_Dequeue:2", shape=(64, 46, 54, 38), dtype=float32, device=/device:CPU:*)
2019-07-12 10:02:57,711 DEBUG Tensor("fifo_queue_Dequeue:2", shape=(64, 46, 54, 38), dtype=float32, device=/device:CPU:*)
[2019-07-12 10:04:40,278] [train] [INFO] define model-
2019-07-12 10:04:40,278 INFO define model-
INFO:tensorflow:Summary name training sample is illegal; using training_sample instead.
2019-07-12 10:05:05,568 INFO Summary name training sample is illegal; using training_sample instead.
INFO:tensorflow:Summary name validation sample is illegal; using validation_sample instead.
2019-07-12 10:05:05,571 INFO Summary name validation sample is illegal; using validation_sample instead.
[2019-07-12 10:05:44,186] [train] [INFO] model weights initialization
2019-07-12 10:05:44,186 INFO model weights initialization
[2019-07-12 10:06:16,156] [train] [INFO] Restore pretrained weights... ./models\pretrained/mobilenet_v2_1.4_224/mobilenet_v2_1.4_224.ckpt
2019-07-12 10:06:16,156 INFO Restore pretrained weights... ./models\pretrained/mobilenet_v2_1.4_224/mobilenet_v2_1.4_224.ckpt
INFO:tensorflow:Restoring parameters from ./models\pretrained/mobilenet_v2_1.4_224/mobilenet_v2_1.4_224.ckpt
2019-07-12 10:06:20,420 INFO Restoring parameters from ./models\pretrained/mobilenet_v2_1.4_224/mobilenet_v2_1.4_224.ckpt
[2019-07-12 10:06:57,048] [train] [INFO] Restore only weights in backbone layers.Key Openpose/MConv_Stage1_L1_1_depthwise/depthwise_weights not found in checkpoint
	 [[Node: save_1/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2/tensor_names, save_1/RestoreV2/shape_and_slices)]]
	 [[Node: save_1/RestoreV2/_1341 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_312_save_1/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'save_1/RestoreV2', defined at:
  File "c:\Users\smith\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\smith\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd\__main__.py", line 434, in main
    run()
  File "c:\Users\smith\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd\__main__.py", line 312, in run_file
    runpy.run_path(target, run_name='__main__')
  File "D:\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "D:\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "e:\tf-openpose\train.py", line 187, in <module>
    loader = tf.train.Saver(net.restorable_variables(only_backbone=False))
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1284, in __init__
    self.build()
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1296, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1333, in _build
    build_save=build_save, build_restore=build_restore)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 781, in _build_internal
    restore_sequentially, reshape)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 400, in _AddRestoreOps
    restore_sequentially)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 832, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1546, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3414, in create_op
    op_def=op_def)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Key Openpose/MConv_Stage1_L1_1_depthwise/depthwise_weights not found in checkpoint
	 [[Node: save_1/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2/tensor_names, save_1/RestoreV2/shape_and_slices)]]
	 [[Node: save_1/RestoreV2/_1341 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_312_save_1/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

2019-07-12 10:06:57,048 INFO Restore only weights in backbone layers.Key Openpose/MConv_Stage1_L1_1_depthwise/depthwise_weights not found in checkpoint
	 [[Node: save_1/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2/tensor_names, save_1/RestoreV2/shape_and_slices)]]
	 [[Node: save_1/RestoreV2/_1341 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_312_save_1/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'save_1/RestoreV2', defined at:
  File "c:\Users\smith\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\smith\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd\__main__.py", line 434, in main
    run()
  File "c:\Users\smith\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd\__main__.py", line 312, in run_file
    runpy.run_path(target, run_name='__main__')
  File "D:\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "D:\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "e:\tf-openpose\train.py", line 187, in <module>
    loader = tf.train.Saver(net.restorable_variables(only_backbone=False))
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1284, in __init__
    self.build()
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1296, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1333, in _build
    build_save=build_save, build_restore=build_restore)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 781, in _build_internal
    restore_sequentially, reshape)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 400, in _AddRestoreOps
    restore_sequentially)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 832, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1546, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3414, in create_op
    op_def=op_def)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Key Openpose/MConv_Stage1_L1_1_depthwise/depthwise_weights not found in checkpoint
	 [[Node: save_1/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2/tensor_names, save_1/RestoreV2/shape_and_slices)]]
	 [[Node: save_1/RestoreV2/_1341 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_312_save_1/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

INFO:tensorflow:Restoring parameters from ./models\pretrained/mobilenet_v2_1.4_224/mobilenet_v2_1.4_224.ckpt
2019-07-12 10:06:57,456 INFO Restoring parameters from ./models\pretrained/mobilenet_v2_1.4_224/mobilenet_v2_1.4_224.ckpt
[2019-07-12 10:07:34,277] [train] [INFO] Restore pretrained weights...Done
2019-07-12 10:07:34,277 INFO Restore pretrained weights...Done
[2019-07-12 10:08:56,376] [train] [INFO] prepare file writer
2019-07-12 10:08:56,376 INFO prepare file writer
[2019-07-12 10:12:27,613] [train] [INFO] prepare coordinator
2019-07-12 10:12:27,613 INFO prepare coordinator
[2019-07-12 10:12:31,593] [train] [INFO] Training Started.
2019-07-12 10:12:31,593 INFO Training Started.
train_op：
name: "Adam"
op: "AssignAdd"
input: "Variable"
input: "Adam/value"
device: "/device:GPU:*"
attr {
  key: "T"
  value {
    type: DT_INT32
  }
}
attr {
  key: "_class"
  value {
    list {
      s: "loc:@Variable"
    }
  }
}
attr {
  key: "use_locking"
  value {
    b: false
  }
}

global_step：
<tf.Variable 'Variable:0' shape=() dtype=int32_ref>

#### 
Execute to ", gs_num = sess. run ([train_op, global_step])" and no response occurs.

**Comment by smisthzhu** [comment]
![image](https://user-images.githubusercontent.com/10770825/61097517-33083d00-a48e-11e9-90d4-898367d5ec35.png)

**Comment by smisthzhu** [comment]
def get_vectormap(self, target_size):
        vectormap = np.zeros((CocoMetadata.__coco_parts*2, self.height, self.width), dtype=np.float32)
        countmap = np.zeros((CocoMetadata.__coco_parts, self.height, self.width), dtype=np.int16)
        for joints in self.joint_list:
            for plane_idx, (j_idx1, j_idx2) in enumerate(CocoMetadata.__coco_vecs):
                j_idx1 -= 1
                j_idx2 -= 1

                center_from = joints[j_idx1]
                center_to = joints[j_idx2]

                if center_from[0] < -100 or center_from[1] < -100 or center_to[0] < -100 or center_to[1] < -100:
                    continue

                CocoMetadata.put_vectormap(vectormap, countmap, plane_idx, center_from, center_to)

        vectormap = vectormap.transpose((1, 2, 0))
        nonzeros = np.nonzero(countmap)
        for p, y, x in zip(nonzeros[0], nonzeros[1], nonzeros[2]):
            if countmap[p][y][x] <= 0:
                continue
            vectormap[y][x][p*2+0] /= countmap[p][y][x]
            vectormap[y][x][p*2+1] /= countmap[p][y][x]
        print(target_size)
        print(vectormap)
        if target_size:
            vectormap = cv2.resize(vectormap, target_size, interpolation=cv2.INTER_AREA)

        return vectormap.astype(np.float16)

######error:
Traceback (most recent call last):
  File "pose_dataset.py", line 487, in <module>
    TestDataSpeed(df).start()
  File "/root/anaconda3/lib/python3.5/site-packages/tensorpack/dataflow/common.py", line 57, in start
    for idx, dp in enumerate(itr):
  File "/root/anaconda3/lib/python3.5/site-packages/tensorpack/dataflow/common.py", line 293, in __iter__
    ret = self.func(copy(dp))  # shallow copy the list
  File "/home/data/tf-openpose/tf_pose/pose_augment.py", line 267, in pose_to_img
    meta_l[0].get_vectormap(target_size=(_network_w // _scale, _network_h // _scale))
cv2.error: OpenCV(4.1.0) /io/opencv/modules/imgproc/src/resize.cpp:3555: error: (-215:Assertion failed) func != 0 && cn <= 4 in function 'resize'

**Comment by xiaopingxiao** [comment]
Hello, have you solved this problem now? I have also encountered this problem(OpenCV(4.1.0) /io/opencv/modules/imgproc/src/resize.cpp:3555: error: (-215:Assertion failed) func != 0 && cn <= 4 in function 'resize').
When you say you don't feel like you're using a gpu, it's probably because you don't have tensorflow-gpu and cuda installed

**Comment by khan958** [comment]
@xiaopingxiao  Same problem with me. Have you solved this issue?

**Comment by BadMachine** [comment]
@khan958 you need to define images folder path
