### ISSUE TITLE
How to build && run in Docker on Ubuntu

### ISSUE THREAD

**Issue by seralekseenko** [ildoonet/tf-pose-estimation#492]
Hey people :)
Please can someone explain to me how to properly build and run a container for this project. 
Unfortunately, I have not yet been able to successfully build the image))

Ubuntu 19.04

My steps:

1. `git clone git@github.com:ildoonet/tf-pose-estimation.git`
2. `cd tf-pose-estimation`
3. `docker build . -t test` --> OUT:
```
Sending build context to Docker daemon  129.8MB
Step 1/5 : FROM idock.daumkakao.io/kakaobrain/deepcloud-sshd:openpose-preprocess
Get https://idock.daumkakao.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
4. So, I tried build container as described in #103 : `docker build --tag openpose -f ./docker/Dockerfile .` .  --> OUT:
-  Sometimes I get a message: `debconf: delaying package configuration, since apt-utils is not installed`.
- There was one warning during image building:
```
CMake Warning at cmake/OpenCVDetectPython.cmake:81 (message):
  CMake's 'find_host_package(PythonInterp 2.7)' founds wrong Python version:

  PYTHON_EXECUTABLE=/usr/bin/python3

  PYTHON_VERSION_STRING=3.5.2

  Consider specify 'PYTHON2_EXECUTABLE' variable via CMake command line or
  environment variables

Call Stack (most recent call first):
  cmake/OpenCVDetectPython.cmake:275 (find_python)
  CMakeLists.txt:702 (include)

```
- And the image build did not complete, giving an ERROR:
```
Downloading https://files.pythonhosted.org/packages/96/84/9a07b1095fd8555ba3f3d519517c8743c2554a245f9476e5e39869f948d2/pycocotools-2.0.0.tar.gz (1.5MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xumt3eve/pycocotools/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xumt3eve/pycocotools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-xumt3eve/pycocotools/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xumt3eve/pycocotools/setup.py", line 2, in <module>
        from Cython.Build import cythonize
    ImportError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/sh -c cd /root/tf-openpose/ && pip3 install -U setuptools && pip3 install tensorflow && pip3 install -r requirements.txt' returned a non-zero code: 1

```
____
Tell me where am I making a mistake?

I am especially interested in: what am I doing wrong with the first Dockerfile?

**Comment by nyk510** [comment]
@seralekseenko Hi ;) The Dockerfile the repo's author made is a little friendly I think..., so I make the following Dockerfile as

```dockerfile
FROM ubuntu:16.04

RUN apt-get update -yq && apt-get install -yq build-essential cmake git pkg-config wget zip libffi-dev && \
  apt-get install -yq libjpeg8-dev libtiff5-dev libjasper-dev libpng12-dev && \
  apt-get install -yq libavcodec-dev libavformat-dev libswscale-dev libv4l-dev && \
  apt-get install -yq libgtk2.0-dev && \
  apt-get install -yq libatlas-base-dev gfortran && \
  apt-get install -yq python3 python3-dev python3-pip python3-setuptools python3-tk git && \
  rm -rf /tmp/*.tar.gz && \
  apt-get clean && rm -rf /tmp/* /var/tmp* /var/lib/apt/lists/* && \
  rm -f /etc/ssh/ssh_host_* && rm -rf /usr/share/man?? /usr/share/man/??_*

# Install miniconda dir and add path
ENV CONDA_DIR /opt/conda
ENV PATH ${CONDA_DIR}/bin:${PATH}
RUN wget --quiet https://repo.continuum.io/miniconda/Miniconda3-4.5.12-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p ${CONDA_DIR} && \
    rm ~/miniconda.sh

WORKDIR ${HOME}/tf-openpose/
COPY requirements.txt ./

RUN conda install -y cython numpy
RUN pip install -U setuptools pip && \
  pip install  -r requirements.txt

RUN cd ${HOME} && git clone https://github.com/cocodataset/cocoapi && \
  cd cocoapi/PythonAPI && python setup.py build_ext --inplace && python setup.py build_ext install && \
  mkdir /coco && cd /coco && wget -q http://images.cocodataset.org/annotations/annotations_trainval2017.zip && \
  unzip annotations_trainval2017.zip && rm -rf annotations_trainval2017.zip

COPY . .

# install tf-pose
RUN python setup.py install

RUN mkdir ~/.jupyter &&\
  echo "c.NotebookApp.open_browser = False\n\
c.NotebookApp.ip = '*'" | tee -a ${HOME}/.jupyter/jupyter_notebook_config.py

CMD [ "jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--allow-root"]

```
and put in `~/Dockerfile` (`~` means this repo's root dir) and make a `docker-compose.yml` file as follow

```yml
version: '2.3'
services:
  jupyer:
    build: .
    volumes:
      - ./:/analysis
    working_dir: /analysis/notebooks
    tty: true
    ports:
      - 4455:8888
    command: jupyter notebook --ip='*' --NotebookApp.token='' --NotebookApp.password='' --allow-root
```

## SetUp

1. docker-compose build
2. docker-compose up -d
3. access to localhost:4455 and make new notebook and import tf_pose like this

```python
from tf_pose import common
from tf_pose.estimator import TfPoseEstimator
```

If run this, CONGRATULATIONS ;)

**Comment by nyk510** [comment]
`requirements.txt` is like this

```
tensorflow==1.14
argparse
dill
fire
matplotlib
numba
psutil
pycocotools
requests
scikit-image
scipy
slidingwindow
opencv-python
tqdm
git+https://github.com/ppwwyyxx/tensorpack.git

jupyter
notebook
```

**Comment by MadisLemsalu** [comment]
1.sudo apt install swig
2.find / -name "pafprocess.i"
3. cd to that directory where pafprocess.i is located
3. swig -python -c++ pafprocess.i && python3 setup.py build_ext --inplace
