### ISSUE TITLE
Error during runing demo

### ISSUE THREAD

**Issue by AiMizuno** [ildoonet/tf-pose-estimation#498]
ubuntu18.04
cuda10.0
cudnn7.6.1
tensorflow-gpu:1.14.0

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
2019-08-12 11:32:39.884867: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
2019-08-12 11:32:40.412474: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-08-12 11:32:41.195858: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] **Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR**
2019-08-12 11:32:41.215865: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: **Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above**.
	 [[{{node TfPoseEstimator/MobilenetV1/Conv2d_0/Conv2D}}]]
	 [[strided_slice_2-0-0-TransposeNCHWToNHWC-LayoutOptimizer/_11]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node TfPoseEstimator/MobilenetV1/Conv2d_0/Conv2D}}]]

There are some errors on cudnn and I have no idea how to solve it.

**Comment by AiMizuno** [comment]
Run out of memory

**Comment by QendKrasniqi** [comment]
python 3.7
tensorflow-gpu 2.0

In tf_pose/estimator.py, I replaced line 334:

```python
self.persistent_sess = tf.Session(graph=self.graph, config=tf_config)
```

with the following:

```python
config_proto = tf.ConfigProto()
config_proto.gpu_options.allow_growth = True
self.persistent_sess = tf.Session(graph=self.graph, config=config_proto)
```
