### ISSUE TITLE
Run error: Failed to initialize TensorRT.

### ISSUE THREAD

**Issue by EasonGZY** [ildoonet/tf-pose-estimation#515]
Hi, everyone! I was struggling with the error when I run the code `python run.py --model=mobilenet_thin --resize=432x368 --image=./images/p1.jpg` or`python run_webcam.py --model=mobilenet_thin --resize=432x368 --camera=0`
it has the following  warnings :
/home/guanziyi/anaconda3/envs/tfpose/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/guanziyi/anaconda3/envs/tfpose/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/guanziyi/anaconda3/envs/tfpose/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/guanziyi/anaconda3/envs/tfpose/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/guanziyi/anaconda3/envs/tfpose/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/guanziyi/anaconda3/envs/tfpose/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

**errors:**

**** **Failed to initialize TensorRT. This is either because the TensorRT installation path is not in LD_LIBRARY_PATH, or because you do not have it installed.** If not installed, please go to https://developer.nvidia.com/tensorrt to download and install TensorRT ****
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    from tf_pose import common
  File "/home/guanziyi/tf-pose-estimation/tf_pose/__init__.py", line 5, in <module>
    from tf_pose.runner import infer, Estimator, get_estimator
  File "/home/guanziyi/tf-pose-estimation/tf_pose/runner.py", line 8, in <module>
    from tf_pose import eval
  File "/home/guanziyi/tf-pose-estimation/tf_pose/eval.py", line 13, in <module>
    from tf_pose.estimator import TfPoseEstimator
  File "/home/guanziyi/tf-pose-estimation/tf_pose/estimator.py", line 14, in <module>
    import tensorflow.contrib.tensorrt as trt
  File "/home/guanziyi/anaconda3/envs/tfpose/lib/python3.6/site-packages/tensorflow/contrib/tensorrt/__init__.py", line 34, in <module>
    raise e
  File "/home/guanziyi/anaconda3/envs/tfpose/lib/python3.6/site-packages/tensorflow/contrib/tensorrt/__init__.py", line 25, in <module>
    from tensorflow.contrib.tensorrt.python import *
  File "/home/guanziyi/anaconda3/envs/tfpose/lib/python3.6/site-packages/tensorflow/contrib/tensorrt/python/__init__.py", line 22, in <module>
    from tensorflow.contrib.tensorrt.python.ops import trt_engine_op
  File "/home/guanziyi/anaconda3/envs/tfpose/lib/python3.6/site-packages/tensorflow/contrib/tensorrt/python/ops/trt_engine_op.py", line 32, in <module>
    resource_loader.get_path_to_datafile("_trt_engine_op.so"))
  File "/home/guanziyi/anaconda3/envs/tfpose/lib/python3.6/site-packages/tensorflow/contrib/util/loader.py", line 56, in load_op_library
    ret = load_library.load_op_library(path)
  File "/home/guanziyi/anaconda3/envs/tfpose/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
**tensorflow.python.framework.errors_impl.NotFoundError: libnvinfer.so.4: cannot open shared object file: No such file or directory**

I just install the TensorRT on the /home/guanziyi/tf-pose-estimation/tensorrt_tar/TensorRT-5.1.5.0/ so how can I solve it?

**Comment by sanzanglong** [comment]
undefined estimator.py
import tensorflow.contrib.tensorrt as trt
# import tensorflow.contrib.tensorrt as trt
trt No reference

**Comment by EasonGZY** [comment]
> undefined estimator.py
> import tensorflow.contrib.tensorrt as trt
> 
> # import tensorflow.contrib.tensorrt as trt
> trt No reference

**Comment by EasonGZY** [comment]
> undefined estimator.py
> import tensorflow.contrib.tensorrt as trt
> 
> # import tensorflow.contrib.tensorrt as trt
> trt No reference

@sanzanglong  sorry， I had already done it, but it still didn;t work.

**Comment by chuanenlin** [comment]
I solved it simply by going to \tf-pose\estimator.py and commenting out `import tensorflow.contrib.tensorrt as trt`.

**Comment by MuxiJ** [comment]
> I solved it simply by going to \tf-pose\estimator.py and commenting out `import tensorflow.contrib.tensorrt as trt`.

thank u，it works！
