### ISSUE TITLE
Cannot load file containing pickled data when allow_pickle=False

### ISSUE THREAD

**Issue by mgarbade** [ildoonet/tf-pose-estimation#529]
There seems to be a problem on training with the 'numpy-encoded' vgg, cmu or openpose models.
As far as I can see it, these two versions of numba and numpy are compatible / needed during installation:

```
numba==0.43.1
numpy==1.16.2
```

However, numpy 1.16.2 has some incompatibilites, explained [here](https://github.com/automl/auto-sklearn/issues/667#issuecomment-488615513), leading to the above mentioned error. The full stack trace is:

```
Traceback (most recent call last):
  File "tf_pose/train.py", line 201, in <module>
    net.load(pretrain_path, sess, False)
  File "/home/garbade/libs/tf-pose-estimation/tf_pose/network_base.py", line 78, in load
    data_dict = np.load(data_path, encoding='bytes').item()
  File "/home/garbade/miniconda3/envs/py36_tf_v1.14/lib/python3.6/site-packages/numpy/lib/npyio.py", line 451, in load
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False
```

So changing [this line](https://github.com/ildoonet/tf-pose-estimation/blob/master/tf_pose/network_base.py#L78) to   

    data_dict = np.load(data_path, encoding='bytes', allow_pickle=True).item()

does the trick. (Sorry for boring issue)

**Comment by NargesSayah** [comment]
Doing so gives me the following errors:

`_pickle.UnpicklingError:` invalid load key, '\x00'.

`OSError:` Failed to interpret file 'blahblah' as a pickle
