### ISSUE TITLE
error AttributeError: 'MultiThreadMapData' object has no attribute '_evt' in train

### ISSUE THREAD

**Issue by hihijimin** [ildoonet/tf-pose-estimation#588]
there are 2 problems
1. AttributeError: 'MultiThreadMapData' object has no attribute '_evt'
2. TypeError: __init__() got an unexpected keyword argument 'nr_thread'
how can i solve this problems?

Exception ignored in: <bound method MultiThreadMapData.__del__ of <tensorpack.dataflow.parallel_map.MultiThreadMapData object at 0x7fa5cd53ae48>>
Traceback (most recent call last):
  File "/home/name/.local/lib/python3.6/site-packages/tensorpack/dataflow/parallel_map.py", line 203, in __del__
    if self._evt is not None:
AttributeError: 'MultiThreadMapData' object has no attribute '_evt'
Traceback (most recent call last):
  File "/media/name/D/tf-pose-estimation/tf_pose/train.py", line 72, in <module>
    df_valid = get_dataflow_batch(args.datapath, False, args.batchsize, img_path=args.imgpath)
  File "/media/name/D/tf-pose-estimation/tf_pose/pose_dataset.py", line 394, in get_dataflow_batch
    ds = get_dataflow(path, is_train, img_path=img_path)
  File "/media/name/D/tf-pose-estimation/tf_pose/pose_dataset.py", line 374, in get_dataflow
    ds = MultiThreadMapData(ds, nr_thread=16, map_func=read_image_url, buffer_size=1000)
TypeError: __init__() got an unexpected keyword argument 'nr_thread'
/home/name/.local/lib/python3.6/site-packages/numba/object_mode_passes.py:178: NumbaWarning: Function "get_vectormap" was compiled in object mode without forceobj=True.

**Comment by mshooter** [comment]
Did you solve it? if so could you tell me how
