### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by jairCalderon** [ildoonet/tf-pose-estimation#600]
hola, estoy realizando este proyecto escolar
https://www.youtube.com/watchv=nUjGLjOmF7o&list=RDCMUC2W0aQEPNpU6XrkFCYifRFQ&index=1
pero cuando quiero compilar  " (tfpose) C:\Users\Jair\Desktop\tf-pose-estimation> python run_webcam.py --model=mobilenet_thin --resize=432x368 --camera=0 --tensorrt=True"

me marca el siguiente error

Traceback (most recent call last):
  File "run_webcam.py", line 8, in <module>
    from tf_pose.estimator import TfPoseEstimator
  File "C:\Users\Jair\Desktop\tf-pose-estimation\tf_pose\__init__.py", line 5, in <module>
    from tf_pose.runner import infer, Estimator, get_estimator
  File "C:\Users\Jair\Desktop\tf-pose-estimation\tf_pose\runner.py", line 8, in <module>
    from tf_pose import eval
  File "C:\Users\Jair\Desktop\tf-pose-estimation\tf_pose\eval.py", line 13, in <module>
    from tf_pose.estimator import TfPoseEstimator
  File "C:\Users\Jair\Desktop\tf-pose-estimation\tf_pose\estimator.py", line 14, in <module>
    import tensorflow.contrib.tensorrt as trt
ModuleNotFoundError: No module named 'tensorflow.contrib'

espero que alguien me pueda orientar , soy nuevo en esto de phyto, porfavor.

**Comment by silent-code** [comment]
What version of tensorflow are you running? tensorflow.contrib doesn't exist in tensorflow >= 2.0. 

See this issue: https://github.com/tensorflow/tensorflow/issues/31350

**Comment by hunter6399** [comment]
I got the same error unfortunately TensorFlow has removed* contrib 
I cloned [](https://github.com/gsethi2409/tf-pose-estimation )apparently this works with TF 2

*- Moved to the core/deleted
