### ISSUE TITLE
Error after outputting four epochs

### ISSUE THREAD

**Issue by xuelanlingying** [ildoonet/tf-pose-estimation#603]
I can‘t run train.py. After 4 times epochs, the following error occurs. I changed models, Still the same error

```
2020-04-14 14:13:12.266313: W tensorflow/core/common_runtime/bfc_allocator.cc:237] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.36GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2020-04-14 14:13:12.276830: W tensorflow/core/common_runtime/bfc_allocator.cc:237] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.36GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
[2020-04-14 14:26:31,271] [train] [INFO] epoch=0.03 step=500, 4.7537 examples/sec lr=0.000010, loss=23426.8, loss_ll=11204.5, loss_ll_paf=8532.14, loss_ll_heat=2672.38
2020-04-14 14:26:31,271 INFO epoch=0.03 step=500, 4.7537 examples/sec lr=0.000010, loss=23426.8, loss_ll=11204.5, loss_ll_paf=8532.14, loss_ll_heat=2672.38
[2020-04-14 14:39:47,689] [train] [INFO] epoch=0.07 step=1000, 4.8844 examples/sec lr=0.000010, loss=7167.28, loss_ll=3737.45, loss_ll_paf=2456.08, loss_ll_heat=1281.37
2020-04-14 14:39:47,689 INFO epoch=0.07 step=1000, 4.8844 examples/sec lr=0.000010, loss=7167.28, loss_ll=3737.45, loss_ll_paf=2456.08, loss_ll_heat=1281.37
[2020-04-14 14:53:04,118] [train] [INFO] epoch=0.10 step=1500, 4.9295 examples/sec lr=0.000010, loss=4578.48, loss_ll=2014.89, loss_ll_paf=902.79, loss_ll_heat=1112.1
2020-04-14 14:53:04,118 INFO epoch=0.10 step=1500, 4.9295 examples/sec lr=0.000010, loss=4578.48, loss_ll=2014.89, loss_ll_paf=902.79, loss_ll_heat=1112.1
[2020-04-14 15:06:20,379] [train] [INFO] epoch=0.13 step=2000, 4.9527 examples/sec lr=0.000010, loss=4328, loss_ll=1787.67, loss_ll_paf=684.11, loss_ll_heat=1103.56
2020-04-14 15:06:20,379 INFO epoch=0.13 step=2000, 4.9527 examples/sec lr=0.000010, loss=4328, loss_ll=1787.67, loss_ll_paf=684.11, loss_ll_heat=1103.56
358it [00:51,  6.91it/s]
[2020-04-14 15:09:02,043] [train] [INFO] validation(2864) test loss=4101.419732, loss_ll=1695.675923, loss_ll_paf=629.919122, loss_ll_heat=1065.756800
2020-04-14 15:09:02,043 INFO validation(2864) test loss=4101.419732, loss_ll=1695.675923, loss_ll_paf=629.919122, loss_ll_heat=1065.756800
2020-04-14 15:09:02.064046: W tensorflow/core/kernels/queue_base.cc:277] _0_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "train.py", line 261, in <module>
    feed_dict={q_inp: np.array((sample_image + val_image) * max(1, (args.batchsize // 4)))}
  File "C:\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)
  File "C:\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\client\session.py", line 1149, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (26, 184, 184, 3) for Tensor 'fifo_queue_Dequeue:0', which has shape '(8, 184, 184, 3)'
```

Any idea? thanks.

**Comment by Sangerspyro** [comment]
As far as I know, you will need to train it with a batch size of 16. If you cant train it with a batch size of 16, follow these steps:

If you see estimator.py, in the line
`feed_dict={q_inp: np.array((sample_image + val_image) * max(1, (args.batchsize // 16)))}`
 we are taking a sum of sample_image and val_image. 

Let me give you an example. I want to train it with a batch size of 4, then I would do the following
a) Change `sample_train = tf.placeholder(tf.float32, shape=(4, 640, 640, 3))` to `sample_train = tf.placeholder(tf.float32, shape=(2, 640, 640, 3))` (4 has been changed to 2).
b) `sample_valid = tf.placeholder(tf.float32, shape=(12, 640, 640, 3))` to `sample_valid = tf.placeholder(tf.float32, shape=(2, 640, 640, 3))` (12 has been changed to 2).
c) `train_img = tf.summary.image('training sample', sample_train, 4)` to `train_img = tf.summary.image('training sample', sample_train, 2)` (same as in (a))
d) `valid_img = tf.summary.image('validation sample', sample_valid, 12)` to `valid_img = tf.summary.image('validation sample', sample_valid, 2)`
e) Replace `sample_image = [enqueuer.last_dp[0][i] for i in range(4)] ` with `sample_image = [enqueuer.last_dp[0][i] for i in range(2)] ` 
f) And finally replace `feed_dict={q_inp: np.array((sample_image + val_image) * max(1, (args.batchsize // 16)))}` with `feed_dict={q_inp: np.array((sample_image + val_image) * max(1, (args.batchsize // 4)))}` (I changed it from 16 to 4 because the sum of sample_image and val_image is 4, even though the max function is present).

Don't forget to change the images in common.py. Here, I have the number of validation images from 12 to 2, so keep only 2 images in get_sample_images function of common.py

(The original solution was posed by @Naykira in #287)
