### ISSUE TITLE
ImportError: cannot import name 'abs'

### ISSUE THREAD

**Issue by ntysall** [ildoonet/tf-pose-estimation#630]
Hello! 
I was following this tutorial https://www.youtube.com/watch?v=4FZrE3cmTPA, and I keep getting this error:
C:\Users\18572\Documents\Other\pose estimation\tf-pose-estimation-master>python run_webcam.py --camera PexelsVideos2360558.mp4
2020-07-07 11:18:16.192773: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-07-07 11:18:16.199061: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "run_webcam.py", line 8, in <module>
    from tf_pose.estimator import TfPoseEstimator
  File "C:\Users\18572\Documents\Other\pose estimation\tf-pose-estimation-master\tf_pose\__init__.py", line 5, in <module>
    from tf_pose.runner import infer, Estimator, get_estimator
  File "C:\Users\18572\Documents\Other\pose estimation\tf-pose-estimation-master\tf_pose\runner.py", line 7, in <module>
    from tf_pose import common
  File "C:\Users\18572\Documents\Other\pose estimation\tf-pose-estimation-master\tf_pose\common.py", line 3, in <module>
    import tensorflow as tf
  File "C:\Users\18572\Desktop\CornellExtensionsInstall\New folder\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\18572\Desktop\CornellExtensionsInstall\New folder\lib\site-packages\tensorflow\python\__init__.py", line 84, in <module>
    from tensorflow.python import keras
  File "C:\Users\18572\Desktop\CornellExtensionsInstall\New folder\lib\site-packages\tensorflow\python\keras\__init__.py", line 27, in <module>
    from tensorflow.python.keras import models
  File "C:\Users\18572\Desktop\CornellExtensionsInstall\New folder\lib\site-packages\tensorflow\python\keras\models\__init__.py", line 21, in <module>
    from tensorflow.python.keras._impl.keras.models import load_model
  File "C:\Users\18572\Desktop\CornellExtensionsInstall\New folder\lib\site-packages\tensorflow\python\keras\_impl\keras\__init__.py", line 21, in <module>
    from tensorflow.python.keras._impl.keras import activations
  File "C:\Users\18572\Desktop\CornellExtensionsInstall\New folder\lib\site-packages\tensorflow\python\keras\_impl\keras\activations.py", line 23, in <module>
    from tensorflow.python.keras._impl.keras import backend as K
  File "C:\Users\18572\Desktop\CornellExtensionsInstall\New folder\lib\site-packages\tensorflow\python\keras\_impl\keras\backend.py", line 36, in <module>
    from tensorflow.python.layers import base as tf_base_layers
  File "C:\Users\18572\Desktop\CornellExtensionsInstall\New folder\lib\site-packages\tensorflow\python\layers\base.py", line 25, in <module>
    from tensorflow.python.keras import backend
  File "C:\Users\18572\Desktop\CornellExtensionsInstall\New folder\lib\site-packages\tensorflow\python\keras\backend\__init__.py", line 22, in <module>
    from tensorflow.python.keras._impl.keras.backend import abs
ImportError: cannot import name 'abs'

I know that it might have something to do with the version of tensorflow that I'm using, but I don't know what version to use, or what is wrong. Thank you!

**Comment by rdutta1999** [comment]
Are you using a GPU to run this? I would suggest using `Tensorflow=1.14`, `Cudatoolkit=10.0.130` and `Cudnn=7.6.5`. To install all these without any hassle, simply run `conda install tensorflow-gpu==1.14.0` or `conda install tensorflow==1.14.0` depending on whether you are using a GPU or not. This takes care of installing the proper compatible versions of both Tensorflow and Cuda, and since the Cuda is installed in a particular environment and not system-wide, you can easily have multiple Cuda versions in different environments.
