### ISSUE TITLE
Cannot run the system on webcam

### ISSUE THREAD

**Issue by fedeGCT** [ildoonet/tf-pose-estimation#631]
I've followed the installation steps from the repository and also the ones on this video  https://www.youtube.com/watch?v=nUjGLjOmF7o&list=PLtGxQCMEpAN_O1GsDts0bel9Uz2OtBCLz&index=2&t=808s and yet i get the following error whenever I try to run it with a webcam 
(tfpose) C:\Users\Usuario\Desktop\tf-pose-estimation>python run_webcam.py --model=mobilenet_thin --resize=432x368 --camera=0
Traceback (most recent call last):
  File "run_webcam.py", line 8, in <module>
    from tf_pose.estimator import TfPoseEstimator
  File "C:\Users\Usuario\Desktop\tf-pose-estimation\tf_pose\__init__.py", line 5, in <module>
    from tf_pose.runner import infer, Estimator, get_estimator
  File "C:\Users\Usuario\Desktop\tf-pose-estimation\tf_pose\runner.py", line 7, in <module>
    from tf_pose import common
  File "C:\Users\Usuario\Desktop\tf-pose-estimation\tf_pose\common.py", line 3, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

**Comment by fedeGCT** [comment]
By the way i'm using anaconda to set this up

**Comment by rdutta1999** [comment]
Did you create a new environment for this or are using the "base" environment? Run `conda list` in Anaconda Prompt in the particular environment where you are working with this repository, and check if `Tensorflow` is installed.
