### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by dhanush07-star** [ildoonet/tf-pose-estimation#646]
(base) C:\Users\Dhanush\Desktop\pose estimation\tf-pose-estimation-master> python run.py --model=mobilenet_thin --resize=432x368 --image= p1.jpg
2020-09-24 05:50:12.571114: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-09-24 05:50:12.580714: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    from tf_pose import common
  File "C:\Users\Dhanush\Desktop\pose estimation\tf-pose-estimation-master\tf_pose\__init__.py", line 5, in <module>
    from tf_pose.runner import infer, Estimator, get_estimator
  File "C:\Users\Dhanush\Desktop\pose estimation\tf-pose-estimation-master\tf_pose\runner.py", line 8, in <module>
    from tf_pose import eval
  File "C:\Users\Dhanush\Desktop\pose estimation\tf-pose-estimation-master\tf_pose\eval.py", line 13, in <module>
    from tf_pose.estimator import TfPoseEstimator
  File "C:\Users\Dhanush\Desktop\pose estimation\tf-pose-estimation-master\tf_pose\estimator.py", line 14, in <module>
    import tensorflow.contrib.tensorrt as trt
ModuleNotFoundError: No module named 'tensorflow.contrib'

**Comment by WSU-Car** [comment]
i got the same error. From what I found so far, it has to do with the tensorflow version. But even after downgrading from 2.0 to 1.15, I get the same error.

**Comment by danielSoler93** [comment]
Works for me downgrading to tensorflow==1.14. For GPU use,  cuda==10.0 CUDNN==7.6.5

Hope it helps (:

**Comment by WSU-Car** [comment]
Yes, that worked for me too. I had to downgrade to 1.14 as well.

**Comment by d3-worgan** [comment]
Hi I got the same error. Can anyone give a clue to why I cant downgrade my tensorflow version? I am using conda environment on windows. This is the message I get:
```
(tf_pose_calib_env) PS E:\tf-pose-estimation> pip install "tensorflow==1.14"
ERROR: Could not find a version that satisfies the requirement tensorflow==1.14 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1)
ERROR: No matching distribution found for tensorflow==1.14
```

Is everyone else on Linux? Should this work on windows?

**Comment by sajjadh** [comment]
@WSU-Car @danielSoler93 I am using tf 1.14.0 CPU version, but I get this error "No module named 'tensorflow.contrib.tensorrt". As I found they have removed the contrib support for tf 2.x, but it should support 1.x.
Any idea on this?

**Comment by kaisark** [comment]
downgraded to tensorflow 1.14 and it worked.

pip3 install tensorflow==1.14

--------------
System: (Virtualized)
Host: Windows 10
Oracle Virtualbox 6.1 (extension pack/guest additions)
Ubuntu 18 Guest OS
Python 3.6.9
pip 9.0.1

![out](https://user-images.githubusercontent.com/3580312/97116137-84632c80-16d1-11eb-8e74-8bf7e30bf999.gif)

**Comment by PhotonicTree** [comment]
> downgraded to tensorflow 1.14 and it worked.
> 
> pip3 install tensorflow==1.14
>

What if i have this message: 

ERROR: Could not find a version that satisfies the requirement tensorflow==1.14 (from versions: none)
ERROR: No matching distribution found for tensorflow==1.14
?

**Comment by Andrew-Ma-2001** [comment]
> > downgraded to tensorflow 1.14 and it worked.
> > pip3 install tensorflow==1.14
> 
> What if i have this message:
> 
> ERROR: Could not find a version that satisfies the requirement tensorflow==1.14 (from versions: none)
> ERROR: No matching distribution found for tensorflow==1.14
> ?

I have the same question also. I guess is the version of tensorflow is too old,  so I search directly on the webside pypi/samples. It turns out that some of the old version of tensorflow still exists in the webside however most of it's old version has been cleaned out. Next step I will check out the docs of the model tensorflow.contrib and try to find out a way to avoid using it or changing it to a way that could use in a higher version of tensorflow.

**Comment by sajjadh** [comment]
I tried to sort this issue but couldn't find a quick solution, so i switched to colab version. i would suggest that to anyone who whishes only to generate the skeleton data, btw it was the original openPose colab veersion. give it a try.

**Comment by Andrew-Ma-2001** [comment]
Yeah I agree that using the colab version should be the most easiest one. Here are some solutions that I think might be helpful for someone who really want to fix this problem, 
- Solution1 : you can go straightly to the github sorce of tensorflow and build an own tensorflow-gpu 1.14.0 wheel for your self to install it  by pip  https://www.tensorflow.org/install/source_windows#tested_build_configurations
- Solution2 : the probelm now is that the model contrib has been divided into three parts in the lastest tf version: tf.keras.layers.Layer, tf.keras.Model, tf.Module.  It will be super hard to deal with all the codes

**Comment by R-abodyak** [comment]
I'm still stuck in this .. I downgrade to 1.14 but still have the same issue :(
