### ISSUE TITLE
ValueError when running run.py

### ISSUE THREAD

**Issue by Anqi-nus** [ildoonet/tf-pose-estimation#673]
When I was testing the demo script 
`python run.py --model=mobilenet_thin --resize=432x368 --image=./images/p1.jpg`

It gives the following warning and error traceback:

WARNING:tensorflow:From /home/conex/tf-pose-estimation/tf_pose/mobilenet/mobilenet.py:369: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.

Traceback (most recent call last):WARNING:tensorflow:From /home/conex/tf-pose-estimation/tf_pose/mobilenet/mobilenet.py:369: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.

Traceback (most recent call last):
  File "run.py", line 6, in <module>
    from tf_pose import common
  File "/home/conex/tf-pose-estimation/tf_pose/__init__.py", line 5, in <module>
    from tf_pose.runner import infer, Estimator, get_estimator
  File "/home/conex/tf-pose-estimation/tf_pose/runner.py", line 8, in <module>
    from tf_pose import eval
  File "/home/conex/tf-pose-estimation/tf_pose/eval.py", line 16, in <module>
    from pycocotools.coco import COCO
  File "/home/conex/anaconda3/envs/train/lib/python3.7/site-packages/pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/home/conex/anaconda3/envs/train/lib/python3.7/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

  File "run.py", line 6, in <module>
    from tf_pose import common
  File "/home/conex/tf-pose-estimation/tf_pose/__init__.py", line 5, in <module>
    from tf_pose.runner import infer, Estimator, get_estimator
  File "/home/conex/tf-pose-estimation/tf_pose/runner.py", line 8, in <module>
    from tf_pose import eval
  File "/home/conex/tf-pose-estimation/tf_pose/eval.py", line 16, in <module>
    from pycocotools.coco import COCO
  File "/home/conex/anaconda3/envs/train/lib/python3.7/site-packages/pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/home/conex/anaconda3/envs/train/lib/python3.7/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

My environmental settings are:
  Ubuntu 18.04
  python=3.7.9
  tensorflow-gpu=1.15
  cudatoolkit=10.0
  cudnn-7.6.5

Please help!!

**Comment by Anqi-nus** [comment]
`conda install tensorflow-gpu=1.15 `  install Numpy 1.19.2 automatically
updating Numpy version from 1.19.2 to 1.20.0 solves the incompatibility problem
