### ISSUE TITLE
Unable to train due to shape mismatch

### ISSUE THREAD

**Issue by ssq6** [ildoonet/tf-pose-estimation#74]
I am trying to train with coco dataset and keeps hitting shape mismatch errors. Below is an example of training mobilenet_thin model. Any ideas on how to resolve this? Thanks in advance!

/home/sq/p3venv/bin/python /opt/pycharm-community-2017.3.3/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 33467 --file /home/sq/tf-pose-estimation/src/train.py --model=mobilenet_thin --batchsize=96 --lr=0.001 --modelpath=./models/trained-2018-1/ --input-width=368 --input-height=368
pydev debugger: process 11742 is connecting

Connected to pydev debugger (build 173.4301.16)
[2018-02-02 10:47:39,416] [train] [INFO] define model+
loading annotations into memory...
[2018-02-02 10:47:39,420] [pose_dataset] [INFO] dataflow img_path=/home/sq/Downloads/COCO/
Done (t=6.90s)
creating index...
[2018-02-02 10:47:46,700] [pose_dataset] [INFO] /home/sq/Downloads/COCO/annotations dataset 118287
index created!
[0202 10:47:46 @parallel.py:178] [MultiProcessPrefetchData] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
[0202 10:47:47 @parallel.py:178] [MultiProcessPrefetchData] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
loading annotations into memory...
[2018-02-02 10:47:48,163] [pose_dataset] [INFO] dataflow img_path=/home/sq/Downloads/COCO/
Done (t=2.01s)
creating index...
[2018-02-02 10:47:50,300] [pose_dataset] [INFO] /home/sq/Downloads/COCO/annotations dataset 5000
index created!
[0202 10:47:50 @parallel.py:178] [MultiProcessPrefetchData] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
[0202 10:47:50 @parallel.py:178] [MultiProcessPrefetchData] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
[2018-02-02 10:47:51,742] [train] [INFO] tensorboard val image: 12
[2018-02-02 10:47:51,742] [train] [INFO] Tensor("fifo_queue_Dequeue:0", shape=(96, 368, 368, 3), dtype=float32, device=/device:GPU:0)
[2018-02-02 10:47:51,743] [train] [INFO] Tensor("fifo_queue_Dequeue:1", shape=(96, 46, 46, 19), dtype=float32, device=/device:GPU:0)
[2018-02-02 10:47:51,743] [train] [INFO] Tensor("fifo_queue_Dequeue:2", shape=(96, 46, 46, 38), dtype=float32, device=/device:GPU:0)
[2018-02-02 10:49:31,062] [train] [INFO] define model-
2018-02-02 10:49:58.364381: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-02-02 10:49:59.067649: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:895] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-02-02 10:49:59.068058: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1105] Found device 0 with properties: 
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.645
pciBusID: 0000:01:00.0
totalMemory: 7.89GiB freeMemory: 6.97GiB
2018-02-02 10:49:59.068082: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
[2018-02-02 10:50:00,905] [train] [INFO] model weights initialization
[2018-02-02 10:50:12,381] [train] [INFO] Restore pretrained weights...
Traceback (most recent call last):
  File "/home/sq/p3venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1350, in _do_call
    return fn(*args)
  File "/home/sq/p3venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1329, in _run_fn
    status, run_metadata)
  File "/home/sq/p3venv/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [3,3,384,1] rhs shape= [3,3,512,1]
	 [[Node: save_1/Assign_4 = Assign[T=DT_FLOAT, _class=["loc:@MobilenetV1/Conv2d_10_depthwise/depthwise_weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](MobilenetV1/Conv2d_10_depthwise/depthwise_weights, save_1/RestoreV2_4/_25)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pycharm-community-2017.3.3/helpers/pydev/pydevd.py", line 1668, in <module>
    main()
  File "/opt/pycharm-community-2017.3.3/helpers/pydev/pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/pycharm-community-2017.3.3/helpers/pydev/pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/pycharm-community-2017.3.3/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/sq/tf-pose-estimation/src/train.py", line 186, in <module>
    loader.restore(sess, pretrain_path)
  File "/home/sq/p3venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1686, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/sq/p3venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/sq/p3venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/sq/p3venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/home/sq/p3venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [3,3,384,1] rhs shape= [3,3,512,1]
	 [[Node: save_1/Assign_4 = Assign[T=DT_FLOAT, _class=["loc:@MobilenetV1/Conv2d_10_depthwise/depthwise_weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](MobilenetV1/Conv2d_10_depthwise/depthwise_weights, save_1/RestoreV2_4/_25)]]

Caused by op 'save_1/Assign_4', defined at:
  File "/opt/pycharm-community-2017.3.3/helpers/pydev/pydevd.py", line 1668, in <module>
    main()
  File "/opt/pycharm-community-2017.3.3/helpers/pydev/pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/pycharm-community-2017.3.3/helpers/pydev/pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/pycharm-community-2017.3.3/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/sq/tf-pose-estimation/src/train.py", line 185, in <module>
    loader = tf.train.Saver(net.restorable_variables())
  File "/home/sq/p3venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1239, in __init__
    self.build()
  File "/home/sq/p3venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1248, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/sq/p3venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1284, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/sq/p3venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 765, in _build_internal
    restore_sequentially, reshape)
  File "/home/sq/p3venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 440, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/home/sq/p3venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 160, in restore
    self.op.get_shape().is_fully_defined())
  File "/home/sq/p3venv/lib/python3.5/site-packages/tensorflow/python/ops/state_ops.py", line 276, in assign
    validate_shape=validate_shape)
  File "/home/sq/p3venv/lib/python3.5/site-packages/tensorflow/python/ops/gen_state_ops.py", line 59, in assign
    use_locking=use_locking, name=name)
  File "/home/sq/p3venv/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/sq/p3venv/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/home/sq/p3venv/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [3,3,384,1] rhs shape= [3,3,512,1]
	 [[Node: save_1/Assign_4 = Assign[T=DT_FLOAT, _class=["loc:@MobilenetV1/Conv2d_10_depthwise/depthwise_weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](MobilenetV1/Conv2d_10_depthwise/depthwise_weights, save_1/RestoreV2_4/_25)]]

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 29, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt

Process finished with exit code 1

**Comment by ouceduxzk** [comment]
most like the errors comes from you mobilenet configuration, note that mobilenet has alpha to control how thin is the network, # of channels in each layer, here 384 is 0.75 * 512 , so check what kind of pretrained model you loaded and what kind of model you defined

**Comment by ssq6** [comment]
Thanks for the quick response @ouceduxzk!
I was using the mobilenet_v1_1.0_224.ckpt downloaded from the links provided in ~/tf-pose-estimation/models/pretrained/mobilenet_v1_1.0_224_2017_06_14/download.sh
0.75 rings a bell, could this have come from the conv_width config in networks.py?

    elif type == 'mobilenet_thin':
        net = MobilenetNetworkThin({'image': placeholder_input}, conv_width=0.75, conv_width2=0.50, trainable=trainable)
        pretrain_path = 'pretrained/mobilenet_v1_0.75_224_2017_06_14/mobilenet_v1_1.0_224.ckpt'
        last_layer = 'MConv_Stage6_L{aux}_5'

BTW, the pretrain_path looks incorrect, it should be pretrained/mobilenet_v1_1.0_224_2017_06_14/mobilenet_v1_1.0_224.ckpt

**Comment by ssq6** [comment]
Bingo, changed conv_width=1 fixed the problem, thanks a lot!

**Comment by todd95** [comment]
pretrained/ X.X has to match with conv_width=X.X in networks.py def get_network() function
