### ISSUE TITLE
quesition about run.py

### ISSUE THREAD

**Issue by nuptwuchen** [ildoonet/tf-pose-estimation#87]
(py3) wuchen@ubuntu-All-Series-Invalid-entry-length-16-Fixed-up-to-11:~/download/tf-pose-estimation/src$ python3 train.py --model=mobilenet --datapath='/zteam/cocoapi/annotations' --imgpath='/zteam/cocoapi/images/' --batchsize=64 --lr=0.001 --modelpath='/home/wuchen/download/tf-pose-estimation/models/new'
[2018-02-08 14:43:44,345] [train] [INFO] define model+
[2018-02-08 14:43:44,346] [pose_dataset] [INFO] dataflow img_path=/zteam/cocoapi/images/
loading annotations into memory...
Done (t=5.73s)
creating index...
index created!
[2018-02-08 14:43:50,351] [pose_dataset] [INFO] /zteam/cocoapi/annotations dataset 118287
[0208 14:43:50 @parallel.py:178] [MultiProcessPrefetchData] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
[0208 14:43:54 @parallel.py:178] [MultiProcessPrefetchData] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
Traceback (most recent call last):
  File "train.py", line 74, in <module>
    enqueuer = DataFlowToQueue(df, [input_node, heatmap_node, vectmap_node], queue_size=100)
  File "/home/wuchen/download/tf-pose-estimation/src/pose_dataset.py", line 393, in __init__
    self.daemon = True
  File "/home/wuchen/anaconda3/envs/py3/lib/python3.5/threading.py", line 1137, in daemon
    raise RuntimeError("Thread.__init__() not called")
RuntimeError: Thread.__init__() not called

i do not know how to solve it. If u can help me, thanks

**Comment by nuptwuchen** [comment]
i solve it
-        super().__init__()
+        super(DataFlowToQueue).__init__()
I change it back and it works.
however
NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./models/pretrained/mobilenet_v1_0.75_224_2017_06_14/mobilenet_v1_0.75_224.ckpt
         [[Node: save_1/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_1/tensor_names, save_1/RestoreV2_1/shape_and_slices)]]
         [[Node: save_1/RestoreV2_19/_55 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_140_save_1/RestoreV2_19", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
Does it mean that i shoud down a pretrained model(mobilenet) to train, then get a new model?

**Comment by ildoonet** [comment]
@nuptwuchen Do you have './models/pretrained/mobilenet_v1_0.75_224_2017_06_14/mobilenet_v1_0.75_224.ckpt' in your local disk?

**Comment by nuptwuchen** [comment]
thanks，I download it，it works。However， a new problem occured.
(py3) wuchen@ubuntu-All-Series-Invalid-entry-length-16-Fixed-up-to-11:~/download/tf-pose-estimation$ python3 src/train.py --model=mobilenet --datapath='/zteam/cocoapi/annotations' --imgpath='/zteam/cocoapi/images/' --batchsize=32 --lr=0.001 --modelpath='/home/wuchen/download/tf-pose-estimation/models/new'
[2018-02-08 18:41:39,858] [train] [INFO] define model+
[2018-02-08 18:41:39,859] [pose_dataset] [INFO] dataflow img_path=/zteam/cocoapi/images/
loading annotations into memory...
Done (t=5.76s)
creating index...
index created!
[2018-02-08 18:41:45,884] [pose_dataset] [INFO] /zteam/cocoapi/annotations dataset 118287
[0208 18:41:45 @parallel.py:178] [MultiProcessPrefetchData] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
[0208 18:41:51 @parallel.py:178] [MultiProcessPrefetchData] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
[2018-02-08 18:41:51,511] [pose_dataset] [INFO] dataflow img_path=/zteam/cocoapi/images/
loading annotations into memory...
Done (t=2.31s)
creating index...
index created!
[2018-02-08 18:41:54,067] [pose_dataset] [INFO] /zteam/cocoapi/annotations dataset 5000
[0208 18:41:54 @parallel.py:178] [MultiProcessPrefetchData] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
[0208 18:41:54 @parallel.py:178] [MultiProcessPrefetchData] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
[2018-02-08 18:41:57,011] [train] [INFO] tensorboard val image: 12
[2018-02-08 18:41:57,017] [train] [INFO] Tensor("fifo_queue_Dequeue:0", shape=(32, 368, 368, 3), dtype=float32, device=/device:GPU:0)
[2018-02-08 18:41:57,020] [train] [INFO] Tensor("fifo_queue_Dequeue:1", shape=(32, 92, 92, 19), dtype=float32, device=/device:GPU:0)
[2018-02-08 18:41:57,022] [train] [INFO] Tensor("fifo_queue_Dequeue:2", shape=(32, 92, 92, 38), dtype=float32, device=/device:GPU:0)
[2018-02-08 18:42:37,476] [train] [INFO] define model-
2018-02-08 18:42:45.740508: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-02-08 18:42:45.747593: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-02-08 18:42:45.747669: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-02-08 18:42:45.747739: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-02-08 18:42:45.747812: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2018-02-08 18:42:48.116796: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties:
name: TITAN Xp
major: 6 minor: 1 memoryClockRate (GHz) 1.582
pciBusID 0000:05:00.0
Total memory: 11.90GiB
Free memory: 11.40GiB
2018-02-08 18:42:49.941346: W tensorflow/stream_executor/cuda/cuda_driver.cc:523] A non-primary context 0x5645325ded30 exists before initializing the StreamExecutor. We haven't verified StreamExecutor works with that.
2018-02-08 18:42:49.942354: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 1 with properties:
name: TITAN Xp
major: 6 minor: 1 memoryClockRate (GHz) 1.582
pciBusID 0000:06:00.0
Total memory: 11.90GiB
Free memory: 11.74GiB
2018-02-08 18:42:49.960232: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 1
2018-02-08 18:42:49.960336: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y Y
2018-02-08 18:42:49.960408: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 1:   Y Y
2018-02-08 18:42:49.960479: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN Xp, pci bus id: 0000:05:00.0)
2018-02-08 18:42:49.960544: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:1) -> (device: 1, name: TITAN Xp, pci bus id: 0000:06:00.0)
[2018-02-08 18:42:51,510] [train] [INFO] model weights initialization
[2018-02-08 18:43:00,920] [train] [INFO] Restore pretrained weights...
2018-02-08 18:43:05.432143: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.432555: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.433007: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.435864: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
         [[Node: save_1/RestoreV2_9 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_9/tensor_names, save_1/RestoreV2_9/shape_and_slices)]]
2018-02-08 18:43:05.436018: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.437908: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
         [[Node: save_1/RestoreV2_9 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_9/tensor_names, save_1/RestoreV2_9/shape_and_slices)]]
2018-02-08 18:43:05.438608: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
         [[Node: save_1/RestoreV2_9 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_9/tensor_names, save_1/RestoreV2_9/shape_and_slices)]]
2018-02-08 18:43:05.439009: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
         [[Node: save_1/RestoreV2_9 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_9/tensor_names, save_1/RestoreV2_9/shape_and_slices)]]
2018-02-08 18:43:05.439601: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.439845: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.440063: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.440306: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.443270: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.443741: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.447904: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.447991: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.447931: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.448414: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.448594: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.451915: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.452064: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.452441: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.455830: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.456309: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.456472: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.461114: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.463852: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.464157: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.467833: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.467868: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.468237: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.468837: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.469280: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.471978: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.475854: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.475923: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.479885: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.479935: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.480059: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.480589: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.481244: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.481732: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.483867: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-02-08 18:43:05.487875: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
Traceback (most recent call last):
  File "/home/wuchen/anaconda3/envs/py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/wuchen/anaconda3/envs/py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/home/wuchen/anaconda3/envs/py3/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/wuchen/anaconda3/envs/py3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.OutOfRangeError: Read less bytes than requested
         [[Node: save_1/RestoreV2_9 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_9/tensor_names, save_1/RestoreV2_9/shape_and_slices)]]
         [[Node: save_1/RestoreV2_42/_7 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_92_save_1/RestoreV2_42", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/train.py", line 186, in <module>
    loader.restore(sess, pretrain_path)
  File "/home/wuchen/anaconda3/envs/py3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1560, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/wuchen/anaconda3/envs/py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/wuchen/anaconda3/envs/py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/wuchen/anaconda3/envs/py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/wuchen/anaconda3/envs/py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: Read less bytes than requested
         [[Node: save_1/RestoreV2_9 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_9/tensor_names, save_1/RestoreV2_9/shape_and_slices)]]
         [[Node: save_1/RestoreV2_42/_7 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_92_save_1/RestoreV2_42", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op 'save_1/RestoreV2_9', defined at:
  File "src/train.py", line 185, in <module>
    loader = tf.train.Saver(net.restorable_variables())
  File "/home/wuchen/anaconda3/envs/py3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1140, in __init__
    self.build()
  File "/home/wuchen/anaconda3/envs/py3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1172, in build
    filename=self._filename)
  File "/home/wuchen/anaconda3/envs/py3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 688, in build
    restore_sequentially, reshape)
  File "/home/wuchen/anaconda3/envs/py3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/wuchen/anaconda3/envs/py3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/wuchen/anaconda3/envs/py3/lib/python3.5/site-packages/tensorflow/python/ops/gen_io_ops.py", line 663, in restore_v2
    dtypes=dtypes, name=name)
  File "/home/wuchen/anaconda3/envs/py3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/wuchen/anaconda3/envs/py3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/wuchen/anaconda3/envs/py3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

OutOfRangeError (see above for traceback): Read less bytes than requested
         [[Node: save_1/RestoreV2_9 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_9/tensor_names, save_1/RestoreV2_9/shape_and_slices)]]
         [[Node: save_1/RestoreV2_42/_7 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_92_save_1/RestoreV2_42", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]



sorry to distub u

**Comment by nuptwuchen** [comment]
@ildoonet Sorry to distub u, I can not solve the above problem. If u can give me some advice, I will be very greateful.
Thanks
