### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by NIEYALI** [ildoonet/tf-pose-estimation#91]
Traceback (most recent call last):
  File "run.py", line 40, in <module>
    humans = e.inference(image, scales=scales)
  File "/Users/juli/Downloads/tf-openpose/src/estimator.py", line 396, in inference
    roi, info = self._get_scaled_img(npimg, scale)
  File "/Users/juli/Downloads/tf-openpose/src/estimator.py", line 318, in _get_scaled_img
    img_h, img_w = npimg.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by NIEYALI** [comment]
Anybody has good idea about it? Thanks a lot .

**Comment by ildoonet** [comment]
@NIEYALI You have to check your image path. I will add a proper error message.
